-- =============================================================================
-- IOM CRM: import 9 NL/EU researched partnership leads (2026-07-14)
-- Paste into Supabase → SQL Editor → Run
-- Project: https://supabase.com/dashboard/project/werfdsobddsijqckymip/sql/new
--
-- Safe:
--   - Does NOT modify existing leads (especially ArtiShock)
--   - Skips duplicates by normalized website domain, then company_name
--   - Leaves id / created_at / updated_at to DB defaults
--   - Owner = Mirjan from auth.users (email ilike '%mirjan%')
--     Explicitly excludes Iva UUID 1dd6199e-25b2-4def-b790-7ce6a372ae53
--     If Mirjan not found, owner_id / owner_email / owner_avatar_url stay null
--   - Drafts only: initial_email_drafted_at and initial_email_sent_at = NULL
--   - No emails are sent
--
-- Regenerated by: node scripts/generate-nl-leads-sql.mjs
-- =============================================================================

-- 0) Confirm ArtiShock already exists (read-only)
select id, company_name, website, owner_id, owner_email, status
from public.crm_leads
where company_name ilike '%ArtiShock%';

-- 1) Insert non-duplicates
with mirjan as (
  select
    u.id,
    u.email,
    coalesce(u.raw_user_meta_data->>'avatar_url', null) as avatar_url
  from auth.users u
  where u.email ilike '%mirjan%'
    and u.id <> '1dd6199e-25b2-4def-b790-7ce6a372ae53'::uuid
  order by u.created_at asc
  limit 1
),
incoming as (
  select *
  from (values
  (
    'Capitola Digital B.V.',
    'https://capitola.nl/',
    '[{"label":"Contact","url":"https://capitola.nl/contact/"}]'::jsonb,
    'Michael Gude',
    'Account Director',
    'michael@capitola.nl',
    '+31 20 845 2965',
    'External 3D and technical production support for Capitola''s immersive projects. IOM can produce optimized GLB and WebAR assets, real-time environments, architectural content, photogrammetry, 360-degree environments, browser-based Three.js experiences, WebGL/WebGPU prototypes and custom interactive viewers.',
    'High-priority partnership prospect. Capitola''s AR, VR, immersive campaign, training and product-presentation work overlaps strongly with IOM''s technical capabilities. Approach as an external specialist or overflow production partner rather than as a competing full-service agency. Michael is publicly presented as an account and new-business contact. Research source: https://capitola.nl/ and https://capitola.nl/contact/',
    'Immersive experience agency creating augmented reality, virtual reality, AI and interactive projects for campaigns, e-commerce, training, brand experiences and digital product presentation.',
    '3D production support for Capitola''s immersive projects',
    'Hi Michael,

I recently explored Capitola''s work in AR, VR and immersive digital experiences, and I saw a strong overlap with the production work I do through IOM — Interactive Object Media.

IOM is a small creative and technical studio focused on interactive 3D software, browser-based Three.js experiences, WebGL and WebGPU development, photogrammetry, 360-degree environments and optimized real-time assets.

My work includes preparing complex models for browser delivery, creating interactive environments, producing WebAR-ready GLB assets and developing custom 3D presentation tools. I also develop the IOM 3D Viewer, a browser and desktop platform for presenting and publishing interactive 3D content.

I am reaching out as a potential external production partner rather than as a competing agency. IOM could support Capitola when a project needs additional capacity for complex 3D assets, architectural environments, browser optimization, 360-degree content or rapid interactive prototypes.

You can see an overview of my work at:
https://iobjectm.com/

I would be happy to send a focused selection of relevant examples and learn whether Capitola sometimes collaborates with independent 3D and technical specialists.

Would you be open to a brief introductory call?

Best regards,

Mirjan Čubrić
IOM — Interactive Object Media
https://iobjectm.com/
iom-production@proton.me',
    null::timestamptz,
    null::timestamptz,
    'warm',
    'new',
    null::date,
    null::numeric,
    '🤝',
    '',
    'Europe/Amsterdam',
    'Amsterdam',
    'Netherlands',
    null::double precision,
    null::double precision
  ),
  (
    'YIPP',
    'https://yipp.nl/',
    '[{"label":"Contact","url":"https://yipp.nl/contact/"}]'::jsonb,
    'Anna Heimbrock',
    'New Business',
    'anna.heimbrock@yipp.nl',
    '+31 20 820 2348',
    'External technical and 3D production support for museum, heritage, nature, science and education projects. IOM can produce real-time environments, browser-based interactive experiences, virtual reconstructions, photogrammetry, 360-degree tours, optimized spatial assets and custom interactive presentation tools.',
    'High-priority cultural and museum lead. IOM could complement YIPP with real-time 3D production, virtual reconstruction, browser-based exploration, photogrammetry, architectural visualization and 360-degree environments. Anna is publicly presented as the new-business contact. Research source: https://yipp.nl/ and https://yipp.nl/contact/',
    'Interactive experience studio producing digital and physical experiences for nature, culture, history, heritage, science, museums and education.',
    'Possible 3D and interactive production collaboration',
    'Hi Anna,

I recently came across YIPP''s work for museums, heritage, nature, science and education, and I wanted to introduce IOM — Interactive Object Media.

IOM is a small creative and technical studio working across interactive 3D, browser-based experiences, photogrammetry, architectural visualization, virtual reconstruction and 360-degree environments.

My work includes optimized real-time 3D pipelines, interactive Three.js experiences, multi-scene virtual tours and custom tools for presenting and exploring complex models and spaces. I also develop the IOM 3D Viewer for browser and desktop use.

I believe IOM could complement YIPP as an external production partner when a project needs additional capacity for a virtual environment, historical reconstruction, interactive spatial experience, optimized web-based model or 360-degree component.

You can see an overview of the studio and current work at:
https://iobjectm.com/

I would be glad to send a focused selection of relevant examples and learn whether YIPP collaborates with independent technical and 3D specialists.

Would you be open to a brief introductory conversation?

Best regards,

Mirjan Čubrić
IOM — Interactive Object Media
https://iobjectm.com/
iom-production@proton.me',
    null::timestamptz,
    null::timestamptz,
    'warm',
    'new',
    null::date,
    null::numeric,
    '🤝',
    '',
    'Europe/Amsterdam',
    'Amsterdam',
    'Netherlands',
    null::double precision,
    null::double precision
  ),
  (
    'Studio Louter',
    'https://www.studiolouter.nl/',
    '[{"label":"Contact","url":"https://www.studiolouter.nl/nl/contact"}]'::jsonb,
    'Juliette Lindhout',
    'Business Development Manager & Senior Project Manager',
    'juliette@studiolouter.nl',
    '+31 20 670 2044',
    'Technical and 3D production support for museum and cultural projects involving virtual reconstruction, interactive environments, architectural visualization, browser-based 3D, 360-degree media, photogrammetry and optimized real-time assets.',
    'High-priority museum and cultural-sector partnership prospect. Studio Louter develops exhibitions, films, multimedia and interactive installations and appears suited to multidisciplinary collaboration. Position IOM as a technical production specialist working within Studio Louter''s concept and creative direction. Research source: https://www.studiolouter.nl/ and https://www.studiolouter.nl/nl/contact',
    'Content-design studio creating museum exhibitions, interpretive experiences, films, multimedia, interactive installations and cultural storytelling projects.',
    'Technical production support for museum experiences',
    'Hi Juliette,

I recently explored Studio Louter''s museum and cultural work and wanted to introduce IOM — Interactive Object Media.

IOM is a small creative and technical studio focused on interactive 3D, browser-based environments, photogrammetry, architectural visualization, virtual reconstruction and 360-degree experiences.

My work includes creating optimized real-time environments, interactive Three.js presentations, multi-scene virtual tours and custom software for exploring complex 3D models and spaces. I also develop the IOM 3D Viewer, which can be used to present interactive 3D content in a browser or standalone desktop application.

I thought there could be a good fit when Studio Louter needs an external technical partner for a project involving virtual reconstruction, spatial visualization, interactive environments, web-based 3D or 360-degree media.

My intention would be to work within your team''s concept and creative direction while taking responsibility for focused technical and production-heavy parts of a project.

You can see an overview of my work at:
https://iobjectm.com/

I would be happy to share a few relevant examples. Would you be open to a brief introduction?

Best regards,

Mirjan Čubrić
IOM — Interactive Object Media
https://iobjectm.com/
iom-production@proton.me',
    null::timestamptz,
    null::timestamptz,
    'warm',
    'new',
    null::date,
    null::numeric,
    '🤝',
    '',
    'Europe/Amsterdam',
    'Amsterdam',
    'Netherlands',
    null::double precision,
    null::double precision
  ),
  (
    'Wonderment by Design',
    'https://www.wonderment.nl/',
    '[]'::jsonb,
    'Jachim van Huut',
    'CCO & Co-Founder',
    'giveme@wonderment.nl',
    '+31 20 671 8020',
    'Specialist 3D and real-time production for immersive installations, permanent experiences and event projects. IOM can provide optimized 3D environments, interactive web modules, 360-degree content, cross-platform spatial assets and rapid WebGL/WebGPU prototypes.',
    'High-priority immersive-design partnership prospect. Wonderment combines physical environments, interaction and digital technology. Approach as external technical production capacity for selected project components rather than a competing agency. Research source: https://www.wonderment.nl/',
    'Immersive design agency creating digital, physical, permanent and event-based experiences for brands, venues and cultural institutions.',
    'Possible collaboration on immersive 3D production',
    'Hi Jachim,

I recently came across Wonderment''s work combining physical environments, storytelling, interaction and digital technology, and I wanted to introduce IOM — Interactive Object Media.

IOM is a small creative and technical studio focused on interactive 3D software, browser-based real-time experiences, optimized 3D pipelines, photogrammetry, 360-degree environments and WebGL/WebGPU experimentation.

My work includes producing real-time environments, optimizing complex models for browser delivery and developing custom interactive presentation tools. I also develop the IOM 3D Viewer, a browser and desktop platform for presenting and publishing interactive 3D content.

I thought IOM could be useful as an external production partner when Wonderment needs additional capacity for a 3D environment, browser-based interactive module, optimized cross-platform asset or technically demanding visual prototype.

You can see an overview of the studio and current experiments at:
https://iobjectm.com/

I would be glad to share a focused selection of relevant work and hear how you normally collaborate with external specialists.

Would you be open to a short introductory call?

Best regards,

Mirjan Čubrić
IOM — Interactive Object Media
https://iobjectm.com/
iom-production@proton.me',
    null::timestamptz,
    null::timestamptz,
    'warm',
    'new',
    null::date,
    null::numeric,
    '🤝',
    '',
    'Europe/Amsterdam',
    'Amsterdam',
    'Netherlands',
    null::double precision,
    null::double precision
  ),
  (
    'Kiss the Frog',
    'https://www.kissthefrog.nl/',
    '[]'::jsonb,
    'Bart van den Berg',
    'Partner',
    'info@kissthefrog.nl',
    '+31 15 240 0100',
    'External 3D, 360-degree and real-time production support for museums and visitor experiences. IOM can provide optimized models, virtual reconstructions, browser and desktop viewers, architectural environments, photogrammetry and real-time simulation assets.',
    'Strong museum and visitor-experience fit. Kiss the Frog produces multimedia tours, games, projections, installations, motion-tracked experiences and real-time simulations. No verified direct email for Bart was identified, so use the public company email and address the message personally to him. Research source: https://www.kissthefrog.nl/',
    'Digital design agency specializing in interactive visitor experiences for museums, science centers, cultural venues and attractions.',
    '3D and 360 production support for visitor experiences',
    'Hi Bart,

I recently reviewed Kiss the Frog''s interactive museum and visitor-experience work and wanted to introduce IOM — Interactive Object Media.

IOM is a small creative and technical studio working across interactive 3D, real-time environments, photogrammetry, architectural visualization, 360-degree virtual tours and custom browser or desktop viewers.

My work includes producing optimized 3D assets, creating virtual environments and reconstructions, developing Three.js-based experiences and building tools for presenting complex models and spaces. One of these tools is the IOM 3D Viewer, which supports interactive model presentation and standalone web publishing.

I believe IOM could support your team when a project requires additional specialist production for a virtual environment, optimized real-time asset, architectural reconstruction, 360-degree experience or interactive spatial presentation.

I am approaching Kiss the Frog as a potential production partner, not as a competing full-service agency. I could take responsibility for specific technical or production-heavy parts of a larger experience.

You can see an overview of my work at:
https://iobjectm.com/

Would you be open to a brief introduction?

Best regards,

Mirjan Čubrić
IOM — Interactive Object Media
https://iobjectm.com/
iom-production@proton.me',
    null::timestamptz,
    null::timestamptz,
    'warm',
    'new',
    null::date,
    null::numeric,
    '🤝',
    '',
    'Europe/Amsterdam',
    'Delft',
    'Netherlands',
    null::double precision,
    null::double precision
  ),
  (
    'DROPSTUFF MEDIA BV',
    'https://dropstuff.nl/',
    '[{"label":"Contact","url":"https://dropstuff.nl/contact/"}]'::jsonb,
    'René van Engelenburg',
    'Artistic & General Director',
    'info@dropstuff.nl',
    '+31 35 677 1912',
    '3D world production, 360-degree environments, spatial documentation, WebGL companion experiences, architectural visualization and technical support for immersive art installations and touring cultural projects.',
    'Strong immersive-culture and public-installation prospect. DROPSTUFF works with AR, VR, spatial media, interactive installations and touring projects. Position IOM as flexible technical production capacity for digital environments, spatial assets, 360-degree experiences and companion web applications. Research source: https://dropstuff.nl/ and https://dropstuff.nl/contact/',
    'Immersive art and media organization producing interactive public experiences and installations for museums, cultural organizations, cities, festivals and events.',
    '3D and web support for immersive public experiences',
    'Hi René,

I recently came across DROPSTUFF''s immersive and public-space projects and wanted to introduce IOM — Interactive Object Media.

IOM is a small creative and technical studio working across interactive 3D, browser-based real-time experiences, 360-degree environments, photogrammetry, architectural visualization and custom presentation tools.

My work includes producing optimized real-time environments, creating interactive Three.js experiences and developing spatial assets that can be reused across installations, desktop applications and browser-based experiences. I also develop the IOM 3D Viewer for presenting and publishing interactive 3D content.

I thought this could be relevant when a DROPSTUFF project needs additional production support for a digital environment, virtual reconstruction, touring installation asset, spatial documentation or WebGL companion experience.

Because IOM is a small studio, I can work flexibly as a specialist collaborator within a larger creative and technical team.

You can see an overview of my work at:
https://iobjectm.com/

I would be happy to share a few relevant examples and learn more about the external partners you normally work with.

Would you be open to a brief introductory call?

Best regards,

Mirjan Čubrić
IOM — Interactive Object Media
https://iobjectm.com/
iom-production@proton.me',
    null::timestamptz,
    null::timestamptz,
    'warm',
    'new',
    null::date,
    null::numeric,
    '🤝',
    '',
    'Europe/Amsterdam',
    'Hilversum',
    'Netherlands',
    null::double precision,
    null::double precision
  ),
  (
    'INVR.SPACE GmbH',
    'https://invr.space/',
    '[]'::jsonb,
    'Sönke Kirchhof',
    'Executive Producer & CEO',
    'mail@invr.space',
    '+49 30 62739884',
    'Production partnership for VR, 360-degree and interactive 3D projects. IOM can support environment production, photogrammetry, architectural reconstruction, 360-degree post-production, optimized real-time assets, web companion experiences and custom interactive viewers.',
    'Strong 360-degree and immersive-storytelling match. INVR.SPACE works across VR production, immersive storytelling, XR platforms, technology development and distribution. Use the public company email because no verified personal work email was identified. Research source: https://invr.space/',
    'Full-service VR and immersive media studio working in 360-degree production, XR platform development, immersive storytelling, technology research and content distribution.',
    'Possible collaboration on VR, 360 and interactive 3D',
    'Hi Sönke,

I recently explored INVR.SPACE''s work in immersive storytelling, 360-degree production and XR, and I wanted to introduce IOM — Interactive Object Media.

IOM is a small creative and technical studio focused on 360-degree environments, photogrammetry, interactive 3D, optimized browser assets, architectural reconstruction and custom real-time viewers.

My work includes building interactive Three.js experiences, preparing complex models for real-time delivery, producing multi-scene virtual tours and developing the IOM 3D Viewer for browser and desktop model presentation.

I thought there might be room for collaboration when your team needs external capacity for environment production, spatial reconstruction, 360-degree post-production, technically optimized 3D content or a browser-based companion experience.

You can see an overview of my current work at:
https://iobjectm.com/

I would be happy to share a focused selection of relevant projects and learn how INVR.SPACE normally collaborates with independent specialists.

Would you be open to a short introductory conversation?

Best regards,

Mirjan Čubrić
IOM — Interactive Object Media
https://iobjectm.com/
iom-production@proton.me',
    null::timestamptz,
    null::timestamptz,
    'warm',
    'new',
    null::date,
    null::numeric,
    '🤝',
    '',
    'Europe/Berlin',
    'Berlin',
    'Germany',
    null::double precision,
    null::double precision
  ),
  (
    'Ocular bv',
    'https://www.ocular.be/',
    '[{"label":"Ocular and dgtgroup","url":"https://www.ocular.be/en/ocular-dgt-group"}]'::jsonb,
    'Nicolas Vanden Avenne',
    'Founder',
    'info@ocular.be',
    '+32 51 58 84 44',
    'External 3D content and environment production for museums, experience centers, digital showrooms, interactive installations and training spaces. IOM can provide architectural environments, optimized real-time assets, web-based viewers, virtual reconstructions, photogrammetry and 360-degree media.',
    'Strong Benelux partnership prospect. Ocular combines immersive storytelling, interactive installations and digital experience production and is connected with dgtgroup. Position IOM as a flexible specialist capable of producing specific 3D, architectural, browser-based and 360-degree components. Research source: https://www.ocular.be/ and https://www.ocular.be/en/ocular-dgt-group',
    'Immersive digital-experience studio creating museum exhibits, experience centers, training environments, interactive installations and digital showrooms.',
    '3D production support for immersive museum and showroom projects',
    'Hi Nicolas,

I recently came across Ocular''s work in museums, digital showrooms and experience centers and wanted to introduce IOM — Interactive Object Media.

IOM is a small creative and technical studio focused on interactive 3D, architectural environments, browser-based viewers, photogrammetry, virtual reconstruction and 360-degree experiences.

My work includes optimizing complex 3D assets for real-time delivery, producing interactive Three.js environments and developing custom tools for presenting models and spaces. I also develop the IOM 3D Viewer, a browser and desktop platform for interactive model presentation and standalone web publishing.

I thought IOM could provide useful external production capacity when an Ocular or dgtgroup project requires complex 3D content, a virtual environment, architectural reconstruction, an interactive model viewer or a 360-degree component.

You can see an overview of my work at:
https://iobjectm.com/

I would be happy to share a few relevant examples and learn whether you collaborate with independent 3D and interactive specialists.

Would you be open to a brief introductory conversation?

Best regards,

Mirjan Čubrić
IOM — Interactive Object Media
https://iobjectm.com/
iom-production@proton.me',
    null::timestamptz,
    null::timestamptz,
    'warm',
    'new',
    null::date,
    null::numeric,
    '🤝',
    '',
    'Europe/Brussels',
    'Zwevezele',
    'Belgium',
    null::double precision,
    null::double precision
  ),
  (
    'RNDR',
    'https://rndr.studio/',
    '[]'::jsonb,
    'Jeroen Barendse',
    'Partner — Design & Art Direction',
    'info@rndr.studio',
    '+31 70 363 5776',
    'Peer-to-peer specialist collaboration on real-time 3D environments, Blender production pipelines, WebGL/WebGPU experiments, interactive architecture, 360-degree components and technical modules for hybrid and immersive experiences.',
    'Specialist collaboration prospect rather than a conventional sales lead. RNDR works across creative coding, interactive installations, generative systems, data visualization and immersive media. Present IOM as a complementary technical and 3D collaborator for selected project modules. Research source: https://rndr.studio/',
    'Interactive media and creative-technology studio working in creative coding, real-time installations, data visualization, hybrid spaces, generative systems and immersive experiences.',
    'Technical collaboration on real-time 3D and hybrid experiences',
    'Hi Jeroen,

I recently explored RNDR''s work in creative coding, interactive installations and hybrid spaces, and I wanted to introduce IOM — Interactive Object Media.

IOM is a small creative and technical studio focused on real-time 3D, interactive Three.js experiences, Blender production pipelines, WebGL and WebGPU experiments, 360-degree environments and custom tools for exploring digital objects and spaces.

My current work includes procedural and real-time visual experiments, browser-based interactive environments and the IOM 3D Viewer, a platform for presenting and publishing optimized 3D content.

RNDR appears closer to a potential creative and technical partner than a conventional client. I thought there could be a useful overlap when a project needs additional production capacity for 3D environments, interactive architecture, spatial assets or technically demanding browser-based visual modules.

You can see an overview of the studio and current work at:
https://iobjectm.com/

I would be glad to exchange work and see whether there is potential for future collaboration.

Would you be open to a short introduction?

Best regards,

Mirjan Čubrić
IOM — Interactive Object Media
https://iobjectm.com/
iom-production@proton.me',
    null::timestamptz,
    null::timestamptz,
    'warm',
    'new',
    null::date,
    null::numeric,
    '🤝',
    '',
    'Europe/Amsterdam',
    'The Hague',
    'Netherlands',
    null::double precision,
    null::double precision
  )
  ) as v (
    company_name, website, links, contact_name, contact_role, email, phone,
    offer, notes, company_focus, initial_email_subject, initial_email_body,
    initial_email_drafted_at, initial_email_sent_at, temperature, status,
    next_follow_up, estimated_value, value_emoji, client_address,
    client_timezone, client_city, client_country, client_lat, client_lon
  )
),
norm as (
  select
    i.*,
    lower(regexp_replace(
      regexp_replace(
        regexp_replace(trim(i.website), '^https?://', '', 'i'),
        '^www\.', '', 'i'
      ),
      '/+$', ''
    )) as website_domain,
    lower(trim(i.company_name)) as company_key
  from incoming i
),
existing as (
  select
    id,
    company_name,
    website,
    lower(regexp_replace(
      regexp_replace(
        regexp_replace(trim(website), '^https?://', '', 'i'),
        '^www\.', '', 'i'
      ),
      '/+$', ''
    )) as website_domain,
    lower(trim(company_name)) as company_key
  from public.crm_leads
),
to_insert as (
  select n.*
  from norm n
  where not exists (
    select 1 from existing e
    where e.website_domain <> ''
      and n.website_domain <> ''
      and e.website_domain = n.website_domain
  )
  and not exists (
    select 1 from existing e
    where e.company_key = n.company_key
  )
)
insert into public.crm_leads (
  company_name,
  website,
  links,
  contact_name,
  contact_role,
  email,
  phone,
  offer,
  notes,
  company_focus,
  initial_email_subject,
  initial_email_body,
  initial_email_drafted_at,
  initial_email_sent_at,
  temperature,
  status,
  next_follow_up,
  estimated_value,
  value_emoji,
  client_address,
  client_timezone,
  client_city,
  client_country,
  client_lat,
  client_lon,
  owner_id,
  owner_email,
  owner_avatar_url
)
select
  t.company_name,
  t.website,
  t.links,
  t.contact_name,
  t.contact_role,
  t.email,
  t.phone,
  t.offer,
  t.notes,
  t.company_focus,
  t.initial_email_subject,
  t.initial_email_body,
  t.initial_email_drafted_at,
  t.initial_email_sent_at,
  t.temperature,
  t.status,
  t.next_follow_up,
  t.estimated_value,
  t.value_emoji,
  t.client_address,
  t.client_timezone,
  t.client_city,
  t.client_country,
  t.client_lat,
  t.client_lon,
  m.id,
  m.email,
  m.avatar_url
from to_insert t
left join mirjan m on true
returning
  company_name,
  website,
  owner_email,
  status,
  temperature,
  value_emoji,
  (initial_email_subject <> '') as has_subject,
  (initial_email_body <> '') as has_body,
  initial_email_sent_at;

-- 2) Outcome report (inserted vs skipped)
with mirjan_check as (
  select count(*)::int as n
  from auth.users
  where email ilike '%mirjan%'
    and id <> '1dd6199e-25b2-4def-b790-7ce6a372ae53'::uuid
),
incoming as (
  select * from (values
  (
    'Capitola Digital B.V.',
    'https://capitola.nl/',
    '[{"label":"Contact","url":"https://capitola.nl/contact/"}]'::jsonb,
    'Michael Gude',
    'Account Director',
    'michael@capitola.nl',
    '+31 20 845 2965',
    'External 3D and technical production support for Capitola''s immersive projects. IOM can produce optimized GLB and WebAR assets, real-time environments, architectural content, photogrammetry, 360-degree environments, browser-based Three.js experiences, WebGL/WebGPU prototypes and custom interactive viewers.',
    'High-priority partnership prospect. Capitola''s AR, VR, immersive campaign, training and product-presentation work overlaps strongly with IOM''s technical capabilities. Approach as an external specialist or overflow production partner rather than as a competing full-service agency. Michael is publicly presented as an account and new-business contact. Research source: https://capitola.nl/ and https://capitola.nl/contact/',
    'Immersive experience agency creating augmented reality, virtual reality, AI and interactive projects for campaigns, e-commerce, training, brand experiences and digital product presentation.',
    '3D production support for Capitola''s immersive projects',
    'Hi Michael,

I recently explored Capitola''s work in AR, VR and immersive digital experiences, and I saw a strong overlap with the production work I do through IOM — Interactive Object Media.

IOM is a small creative and technical studio focused on interactive 3D software, browser-based Three.js experiences, WebGL and WebGPU development, photogrammetry, 360-degree environments and optimized real-time assets.

My work includes preparing complex models for browser delivery, creating interactive environments, producing WebAR-ready GLB assets and developing custom 3D presentation tools. I also develop the IOM 3D Viewer, a browser and desktop platform for presenting and publishing interactive 3D content.

I am reaching out as a potential external production partner rather than as a competing agency. IOM could support Capitola when a project needs additional capacity for complex 3D assets, architectural environments, browser optimization, 360-degree content or rapid interactive prototypes.

You can see an overview of my work at:
https://iobjectm.com/

I would be happy to send a focused selection of relevant examples and learn whether Capitola sometimes collaborates with independent 3D and technical specialists.

Would you be open to a brief introductory call?

Best regards,

Mirjan Čubrić
IOM — Interactive Object Media
https://iobjectm.com/
iom-production@proton.me',
    null::timestamptz,
    null::timestamptz,
    'warm',
    'new',
    null::date,
    null::numeric,
    '🤝',
    '',
    'Europe/Amsterdam',
    'Amsterdam',
    'Netherlands',
    null::double precision,
    null::double precision
  ),
  (
    'YIPP',
    'https://yipp.nl/',
    '[{"label":"Contact","url":"https://yipp.nl/contact/"}]'::jsonb,
    'Anna Heimbrock',
    'New Business',
    'anna.heimbrock@yipp.nl',
    '+31 20 820 2348',
    'External technical and 3D production support for museum, heritage, nature, science and education projects. IOM can produce real-time environments, browser-based interactive experiences, virtual reconstructions, photogrammetry, 360-degree tours, optimized spatial assets and custom interactive presentation tools.',
    'High-priority cultural and museum lead. IOM could complement YIPP with real-time 3D production, virtual reconstruction, browser-based exploration, photogrammetry, architectural visualization and 360-degree environments. Anna is publicly presented as the new-business contact. Research source: https://yipp.nl/ and https://yipp.nl/contact/',
    'Interactive experience studio producing digital and physical experiences for nature, culture, history, heritage, science, museums and education.',
    'Possible 3D and interactive production collaboration',
    'Hi Anna,

I recently came across YIPP''s work for museums, heritage, nature, science and education, and I wanted to introduce IOM — Interactive Object Media.

IOM is a small creative and technical studio working across interactive 3D, browser-based experiences, photogrammetry, architectural visualization, virtual reconstruction and 360-degree environments.

My work includes optimized real-time 3D pipelines, interactive Three.js experiences, multi-scene virtual tours and custom tools for presenting and exploring complex models and spaces. I also develop the IOM 3D Viewer for browser and desktop use.

I believe IOM could complement YIPP as an external production partner when a project needs additional capacity for a virtual environment, historical reconstruction, interactive spatial experience, optimized web-based model or 360-degree component.

You can see an overview of the studio and current work at:
https://iobjectm.com/

I would be glad to send a focused selection of relevant examples and learn whether YIPP collaborates with independent technical and 3D specialists.

Would you be open to a brief introductory conversation?

Best regards,

Mirjan Čubrić
IOM — Interactive Object Media
https://iobjectm.com/
iom-production@proton.me',
    null::timestamptz,
    null::timestamptz,
    'warm',
    'new',
    null::date,
    null::numeric,
    '🤝',
    '',
    'Europe/Amsterdam',
    'Amsterdam',
    'Netherlands',
    null::double precision,
    null::double precision
  ),
  (
    'Studio Louter',
    'https://www.studiolouter.nl/',
    '[{"label":"Contact","url":"https://www.studiolouter.nl/nl/contact"}]'::jsonb,
    'Juliette Lindhout',
    'Business Development Manager & Senior Project Manager',
    'juliette@studiolouter.nl',
    '+31 20 670 2044',
    'Technical and 3D production support for museum and cultural projects involving virtual reconstruction, interactive environments, architectural visualization, browser-based 3D, 360-degree media, photogrammetry and optimized real-time assets.',
    'High-priority museum and cultural-sector partnership prospect. Studio Louter develops exhibitions, films, multimedia and interactive installations and appears suited to multidisciplinary collaboration. Position IOM as a technical production specialist working within Studio Louter''s concept and creative direction. Research source: https://www.studiolouter.nl/ and https://www.studiolouter.nl/nl/contact',
    'Content-design studio creating museum exhibitions, interpretive experiences, films, multimedia, interactive installations and cultural storytelling projects.',
    'Technical production support for museum experiences',
    'Hi Juliette,

I recently explored Studio Louter''s museum and cultural work and wanted to introduce IOM — Interactive Object Media.

IOM is a small creative and technical studio focused on interactive 3D, browser-based environments, photogrammetry, architectural visualization, virtual reconstruction and 360-degree experiences.

My work includes creating optimized real-time environments, interactive Three.js presentations, multi-scene virtual tours and custom software for exploring complex 3D models and spaces. I also develop the IOM 3D Viewer, which can be used to present interactive 3D content in a browser or standalone desktop application.

I thought there could be a good fit when Studio Louter needs an external technical partner for a project involving virtual reconstruction, spatial visualization, interactive environments, web-based 3D or 360-degree media.

My intention would be to work within your team''s concept and creative direction while taking responsibility for focused technical and production-heavy parts of a project.

You can see an overview of my work at:
https://iobjectm.com/

I would be happy to share a few relevant examples. Would you be open to a brief introduction?

Best regards,

Mirjan Čubrić
IOM — Interactive Object Media
https://iobjectm.com/
iom-production@proton.me',
    null::timestamptz,
    null::timestamptz,
    'warm',
    'new',
    null::date,
    null::numeric,
    '🤝',
    '',
    'Europe/Amsterdam',
    'Amsterdam',
    'Netherlands',
    null::double precision,
    null::double precision
  ),
  (
    'Wonderment by Design',
    'https://www.wonderment.nl/',
    '[]'::jsonb,
    'Jachim van Huut',
    'CCO & Co-Founder',
    'giveme@wonderment.nl',
    '+31 20 671 8020',
    'Specialist 3D and real-time production for immersive installations, permanent experiences and event projects. IOM can provide optimized 3D environments, interactive web modules, 360-degree content, cross-platform spatial assets and rapid WebGL/WebGPU prototypes.',
    'High-priority immersive-design partnership prospect. Wonderment combines physical environments, interaction and digital technology. Approach as external technical production capacity for selected project components rather than a competing agency. Research source: https://www.wonderment.nl/',
    'Immersive design agency creating digital, physical, permanent and event-based experiences for brands, venues and cultural institutions.',
    'Possible collaboration on immersive 3D production',
    'Hi Jachim,

I recently came across Wonderment''s work combining physical environments, storytelling, interaction and digital technology, and I wanted to introduce IOM — Interactive Object Media.

IOM is a small creative and technical studio focused on interactive 3D software, browser-based real-time experiences, optimized 3D pipelines, photogrammetry, 360-degree environments and WebGL/WebGPU experimentation.

My work includes producing real-time environments, optimizing complex models for browser delivery and developing custom interactive presentation tools. I also develop the IOM 3D Viewer, a browser and desktop platform for presenting and publishing interactive 3D content.

I thought IOM could be useful as an external production partner when Wonderment needs additional capacity for a 3D environment, browser-based interactive module, optimized cross-platform asset or technically demanding visual prototype.

You can see an overview of the studio and current experiments at:
https://iobjectm.com/

I would be glad to share a focused selection of relevant work and hear how you normally collaborate with external specialists.

Would you be open to a short introductory call?

Best regards,

Mirjan Čubrić
IOM — Interactive Object Media
https://iobjectm.com/
iom-production@proton.me',
    null::timestamptz,
    null::timestamptz,
    'warm',
    'new',
    null::date,
    null::numeric,
    '🤝',
    '',
    'Europe/Amsterdam',
    'Amsterdam',
    'Netherlands',
    null::double precision,
    null::double precision
  ),
  (
    'Kiss the Frog',
    'https://www.kissthefrog.nl/',
    '[]'::jsonb,
    'Bart van den Berg',
    'Partner',
    'info@kissthefrog.nl',
    '+31 15 240 0100',
    'External 3D, 360-degree and real-time production support for museums and visitor experiences. IOM can provide optimized models, virtual reconstructions, browser and desktop viewers, architectural environments, photogrammetry and real-time simulation assets.',
    'Strong museum and visitor-experience fit. Kiss the Frog produces multimedia tours, games, projections, installations, motion-tracked experiences and real-time simulations. No verified direct email for Bart was identified, so use the public company email and address the message personally to him. Research source: https://www.kissthefrog.nl/',
    'Digital design agency specializing in interactive visitor experiences for museums, science centers, cultural venues and attractions.',
    '3D and 360 production support for visitor experiences',
    'Hi Bart,

I recently reviewed Kiss the Frog''s interactive museum and visitor-experience work and wanted to introduce IOM — Interactive Object Media.

IOM is a small creative and technical studio working across interactive 3D, real-time environments, photogrammetry, architectural visualization, 360-degree virtual tours and custom browser or desktop viewers.

My work includes producing optimized 3D assets, creating virtual environments and reconstructions, developing Three.js-based experiences and building tools for presenting complex models and spaces. One of these tools is the IOM 3D Viewer, which supports interactive model presentation and standalone web publishing.

I believe IOM could support your team when a project requires additional specialist production for a virtual environment, optimized real-time asset, architectural reconstruction, 360-degree experience or interactive spatial presentation.

I am approaching Kiss the Frog as a potential production partner, not as a competing full-service agency. I could take responsibility for specific technical or production-heavy parts of a larger experience.

You can see an overview of my work at:
https://iobjectm.com/

Would you be open to a brief introduction?

Best regards,

Mirjan Čubrić
IOM — Interactive Object Media
https://iobjectm.com/
iom-production@proton.me',
    null::timestamptz,
    null::timestamptz,
    'warm',
    'new',
    null::date,
    null::numeric,
    '🤝',
    '',
    'Europe/Amsterdam',
    'Delft',
    'Netherlands',
    null::double precision,
    null::double precision
  ),
  (
    'DROPSTUFF MEDIA BV',
    'https://dropstuff.nl/',
    '[{"label":"Contact","url":"https://dropstuff.nl/contact/"}]'::jsonb,
    'René van Engelenburg',
    'Artistic & General Director',
    'info@dropstuff.nl',
    '+31 35 677 1912',
    '3D world production, 360-degree environments, spatial documentation, WebGL companion experiences, architectural visualization and technical support for immersive art installations and touring cultural projects.',
    'Strong immersive-culture and public-installation prospect. DROPSTUFF works with AR, VR, spatial media, interactive installations and touring projects. Position IOM as flexible technical production capacity for digital environments, spatial assets, 360-degree experiences and companion web applications. Research source: https://dropstuff.nl/ and https://dropstuff.nl/contact/',
    'Immersive art and media organization producing interactive public experiences and installations for museums, cultural organizations, cities, festivals and events.',
    '3D and web support for immersive public experiences',
    'Hi René,

I recently came across DROPSTUFF''s immersive and public-space projects and wanted to introduce IOM — Interactive Object Media.

IOM is a small creative and technical studio working across interactive 3D, browser-based real-time experiences, 360-degree environments, photogrammetry, architectural visualization and custom presentation tools.

My work includes producing optimized real-time environments, creating interactive Three.js experiences and developing spatial assets that can be reused across installations, desktop applications and browser-based experiences. I also develop the IOM 3D Viewer for presenting and publishing interactive 3D content.

I thought this could be relevant when a DROPSTUFF project needs additional production support for a digital environment, virtual reconstruction, touring installation asset, spatial documentation or WebGL companion experience.

Because IOM is a small studio, I can work flexibly as a specialist collaborator within a larger creative and technical team.

You can see an overview of my work at:
https://iobjectm.com/

I would be happy to share a few relevant examples and learn more about the external partners you normally work with.

Would you be open to a brief introductory call?

Best regards,

Mirjan Čubrić
IOM — Interactive Object Media
https://iobjectm.com/
iom-production@proton.me',
    null::timestamptz,
    null::timestamptz,
    'warm',
    'new',
    null::date,
    null::numeric,
    '🤝',
    '',
    'Europe/Amsterdam',
    'Hilversum',
    'Netherlands',
    null::double precision,
    null::double precision
  ),
  (
    'INVR.SPACE GmbH',
    'https://invr.space/',
    '[]'::jsonb,
    'Sönke Kirchhof',
    'Executive Producer & CEO',
    'mail@invr.space',
    '+49 30 62739884',
    'Production partnership for VR, 360-degree and interactive 3D projects. IOM can support environment production, photogrammetry, architectural reconstruction, 360-degree post-production, optimized real-time assets, web companion experiences and custom interactive viewers.',
    'Strong 360-degree and immersive-storytelling match. INVR.SPACE works across VR production, immersive storytelling, XR platforms, technology development and distribution. Use the public company email because no verified personal work email was identified. Research source: https://invr.space/',
    'Full-service VR and immersive media studio working in 360-degree production, XR platform development, immersive storytelling, technology research and content distribution.',
    'Possible collaboration on VR, 360 and interactive 3D',
    'Hi Sönke,

I recently explored INVR.SPACE''s work in immersive storytelling, 360-degree production and XR, and I wanted to introduce IOM — Interactive Object Media.

IOM is a small creative and technical studio focused on 360-degree environments, photogrammetry, interactive 3D, optimized browser assets, architectural reconstruction and custom real-time viewers.

My work includes building interactive Three.js experiences, preparing complex models for real-time delivery, producing multi-scene virtual tours and developing the IOM 3D Viewer for browser and desktop model presentation.

I thought there might be room for collaboration when your team needs external capacity for environment production, spatial reconstruction, 360-degree post-production, technically optimized 3D content or a browser-based companion experience.

You can see an overview of my current work at:
https://iobjectm.com/

I would be happy to share a focused selection of relevant projects and learn how INVR.SPACE normally collaborates with independent specialists.

Would you be open to a short introductory conversation?

Best regards,

Mirjan Čubrić
IOM — Interactive Object Media
https://iobjectm.com/
iom-production@proton.me',
    null::timestamptz,
    null::timestamptz,
    'warm',
    'new',
    null::date,
    null::numeric,
    '🤝',
    '',
    'Europe/Berlin',
    'Berlin',
    'Germany',
    null::double precision,
    null::double precision
  ),
  (
    'Ocular bv',
    'https://www.ocular.be/',
    '[{"label":"Ocular and dgtgroup","url":"https://www.ocular.be/en/ocular-dgt-group"}]'::jsonb,
    'Nicolas Vanden Avenne',
    'Founder',
    'info@ocular.be',
    '+32 51 58 84 44',
    'External 3D content and environment production for museums, experience centers, digital showrooms, interactive installations and training spaces. IOM can provide architectural environments, optimized real-time assets, web-based viewers, virtual reconstructions, photogrammetry and 360-degree media.',
    'Strong Benelux partnership prospect. Ocular combines immersive storytelling, interactive installations and digital experience production and is connected with dgtgroup. Position IOM as a flexible specialist capable of producing specific 3D, architectural, browser-based and 360-degree components. Research source: https://www.ocular.be/ and https://www.ocular.be/en/ocular-dgt-group',
    'Immersive digital-experience studio creating museum exhibits, experience centers, training environments, interactive installations and digital showrooms.',
    '3D production support for immersive museum and showroom projects',
    'Hi Nicolas,

I recently came across Ocular''s work in museums, digital showrooms and experience centers and wanted to introduce IOM — Interactive Object Media.

IOM is a small creative and technical studio focused on interactive 3D, architectural environments, browser-based viewers, photogrammetry, virtual reconstruction and 360-degree experiences.

My work includes optimizing complex 3D assets for real-time delivery, producing interactive Three.js environments and developing custom tools for presenting models and spaces. I also develop the IOM 3D Viewer, a browser and desktop platform for interactive model presentation and standalone web publishing.

I thought IOM could provide useful external production capacity when an Ocular or dgtgroup project requires complex 3D content, a virtual environment, architectural reconstruction, an interactive model viewer or a 360-degree component.

You can see an overview of my work at:
https://iobjectm.com/

I would be happy to share a few relevant examples and learn whether you collaborate with independent 3D and interactive specialists.

Would you be open to a brief introductory conversation?

Best regards,

Mirjan Čubrić
IOM — Interactive Object Media
https://iobjectm.com/
iom-production@proton.me',
    null::timestamptz,
    null::timestamptz,
    'warm',
    'new',
    null::date,
    null::numeric,
    '🤝',
    '',
    'Europe/Brussels',
    'Zwevezele',
    'Belgium',
    null::double precision,
    null::double precision
  ),
  (
    'RNDR',
    'https://rndr.studio/',
    '[]'::jsonb,
    'Jeroen Barendse',
    'Partner — Design & Art Direction',
    'info@rndr.studio',
    '+31 70 363 5776',
    'Peer-to-peer specialist collaboration on real-time 3D environments, Blender production pipelines, WebGL/WebGPU experiments, interactive architecture, 360-degree components and technical modules for hybrid and immersive experiences.',
    'Specialist collaboration prospect rather than a conventional sales lead. RNDR works across creative coding, interactive installations, generative systems, data visualization and immersive media. Present IOM as a complementary technical and 3D collaborator for selected project modules. Research source: https://rndr.studio/',
    'Interactive media and creative-technology studio working in creative coding, real-time installations, data visualization, hybrid spaces, generative systems and immersive experiences.',
    'Technical collaboration on real-time 3D and hybrid experiences',
    'Hi Jeroen,

I recently explored RNDR''s work in creative coding, interactive installations and hybrid spaces, and I wanted to introduce IOM — Interactive Object Media.

IOM is a small creative and technical studio focused on real-time 3D, interactive Three.js experiences, Blender production pipelines, WebGL and WebGPU experiments, 360-degree environments and custom tools for exploring digital objects and spaces.

My current work includes procedural and real-time visual experiments, browser-based interactive environments and the IOM 3D Viewer, a platform for presenting and publishing optimized 3D content.

RNDR appears closer to a potential creative and technical partner than a conventional client. I thought there could be a useful overlap when a project needs additional production capacity for 3D environments, interactive architecture, spatial assets or technically demanding browser-based visual modules.

You can see an overview of the studio and current work at:
https://iobjectm.com/

I would be glad to exchange work and see whether there is potential for future collaboration.

Would you be open to a short introduction?

Best regards,

Mirjan Čubrić
IOM — Interactive Object Media
https://iobjectm.com/
iom-production@proton.me',
    null::timestamptz,
    null::timestamptz,
    'warm',
    'new',
    null::date,
    null::numeric,
    '🤝',
    '',
    'Europe/Amsterdam',
    'The Hague',
    'Netherlands',
    null::double precision,
    null::double precision
  )
  ) as v (
    company_name, website, links, contact_name, contact_role, email, phone,
    offer, notes, company_focus, initial_email_subject, initial_email_body,
    initial_email_drafted_at, initial_email_sent_at, temperature, status,
    next_follow_up, estimated_value, value_emoji, client_address,
    client_timezone, client_city, client_country, client_lat, client_lon
  )
),
norm as (
  select
    i.company_name,
    i.website,
    lower(regexp_replace(
      regexp_replace(
        regexp_replace(trim(i.website), '^https?://', '', 'i'),
        '^www\.', '', 'i'
      ),
      '/+$', ''
    )) as website_domain,
    lower(trim(i.company_name)) as company_key
  from incoming i
)
select
  n.company_name,
  n.website,
  case
    when exists (
      select 1 from public.crm_leads e
      where lower(regexp_replace(
              regexp_replace(
                regexp_replace(trim(e.website), '^https?://', '', 'i'),
                '^www\.', '', 'i'
              ),
              '/+$', ''
            )) = n.website_domain
        and n.website_domain <> ''
    ) then 'present (domain match — inserted or prior)'
    when exists (
      select 1 from public.crm_leads e
      where lower(trim(e.company_name)) = n.company_key
    ) then 'present (company_name match — inserted or prior)'
    else 'MISSING — insert did not land'
  end as outcome,
  (select n from mirjan_check) as mirjan_users_found
from norm n
order by n.company_name;
