-- =============================================================================
-- IOM CRM: import 9 US researched partnership leads (2026-07-14)
-- Paste into Supabase → SQL Editor → Run
-- Project: https://supabase.com/dashboard/project/werfdsobddsijqckymip/sql/new
--
-- Safe:
--   - Does NOT modify existing leads
--   - Skips duplicates by normalized website domain, then company_name
--   - Leaves id / created_at / updated_at to DB defaults
--   - Owner = Mirjan from auth.users (email ilike '%mirjan%')
--     Explicitly excludes Iva UUID 1dd6199e-25b2-4def-b790-7ce6a372ae53
--     If Mirjan not found, owner_* stay null
--   - Drafts only: initial_email_drafted_at and initial_email_sent_at = NULL
--   - No emails are sent
--
-- Regenerated by: node scripts/generate-crm-leads-sql.mjs us
-- =============================================================================

-- 0) Existing leads snapshot for these names/domains (read-only)
select id, company_name, website, owner_email, status
from public.crm_leads
where lower(trim(company_name)) in (
  'bluecadet',
  'ideum',
  'cortina productions',
  'local projects',
  'unified field',
  'rlmg',
  'trivium interactive',
  'luci',
  'hyperquake'
)
or lower(regexp_replace(
     regexp_replace(
       regexp_replace(trim(website), '^https?://', '', 'i'),
       '^www\.', '', 'i'
     ),
     '/+$', ''
   )) in (
  'bluecadet.com',
  'ideum.com',
  'cortinaproductions.com',
  'localprojects.com',
  'unifiedfield.com',
  'rlmg.com',
  'triviuminteractive.com',
  'lucicreative.com',
  'hyperquake.com'
);

-- 1) Insert non-duplicates
with mirjan as (
  select
    u.id,
    u.email,
    coalesce(u.raw_user_meta_data->>'avatar_url', null) as avatar_url
  from auth.users u
  where u.email ilike '%mirjan%'
    and u.id <> '1dd6199e-25b2-4def-b790-7ce6a372ae53'::uuid
  order by u.created_at asc
  limit 1
),
incoming as (
  select *
  from (values
  (
    'Bluecadet',
    'https://www.bluecadet.com/',
    '[{"label":"About and leadership","url":"https://www.bluecadet.com/about"},{"label":"Contact","url":"https://www.bluecadet.com/contact"},{"label":"LinkedIn","url":"https://www.linkedin.com/company/bluecadet-interactive"}]'::jsonb,
    'Rob Hassler',
    'Director of Strategic Partnerships',
    'info@bluecadet.com',
    '',
    'Specialist and overflow 3D production for Bluecadet''s museum, cultural and visitor-experience projects. IOM can support projects with optimized real-time models, interactive Three.js environments, architectural visualization, photogrammetry, virtual reconstruction, 360-degree media, browser-based 3D modules and custom presentation tools.',
    'High-priority partnership prospect. Bluecadet already has strong design and technology capabilities, so the offer should focus on specialized production capacity rather than general experience design. Rob Hassler is currently listed by Bluecadet as Director of Strategic Partnerships. The public general inquiry email should be used because no verified direct public work email was found. Sources: https://www.bluecadet.com/about, https://www.bluecadet.com/contact, https://www.linkedin.com/company/bluecadet-interactive',
    'Experience-design studio combining design, technology and storytelling for museums, cultural institutions, universities, mission-driven organizations and brands. Its work spans interactive media, digital products, websites and experiences in physical spaces.',
    'Specialist 3D support for Bluecadet projects',
    'Hi Rob,

I recently spent some time looking through Bluecadet''s museum, cultural and interactive work and wanted to introduce IOM — Interactive Object Media.

IOM is a small creative and technical studio focused on interactive 3D software, browser-based Three.js experiences, optimized real-time environments, architectural visualization, photogrammetry and 360-degree virtual experiences.

My work includes preparing complex models for browser delivery, creating interactive environments, reconstructing spaces from photographic or architectural material and developing custom tools for presenting 3D content. I also develop the IOM 3D Viewer, a browser and desktop platform for publishing and exploring optimized models.

I am approaching Bluecadet as a potential specialist production partner rather than as a competing experience-design studio. IOM could support your team when a project needs additional capacity for a 3D environment, virtual reconstruction, architectural model, photogrammetry component, 360-degree experience or technically demanding browser-based module.

An overview of my current work is available at:
https://iobjectm.com/

I would be happy to send a focused selection of relevant examples and learn how Bluecadet normally collaborates with independent technical specialists.

Would you be open to a brief introductory conversation?

Best regards,

Mirjan Čubrić
IOM — Interactive Object Media
https://iobjectm.com/
iom-production@proton.me',
    null::timestamptz,
    null::timestamptz,
    'warm',
    'new',
    null::date,
    null::numeric,
    '🤝',
    '1526 Frankford Avenue, Philadelphia, PA 19125, United States',
    'America/New_York',
    'Philadelphia',
    'United States',
    null::double precision,
    null::double precision
  ),
  (
    'Ideum',
    'https://ideum.com/',
    '[{"label":"Team","url":"https://ideum.com/team"},{"label":"Contact and sales","url":"https://ideum.com/contact"},{"label":"Capabilities","url":"https://ideum.com/capabilities"}]'::jsonb,
    'Liz Richardson',
    'Director of Sales & Marketing',
    'sales@ideum.com',
    '+1 505 792 1110 ext. 1',
    'External production support for Ideum''s exhibits, touch displays and public-space installations. IOM can provide optimized 3D assets, interactive spatial environments, photogrammetry, object and site reconstruction, architectural visualization, 360-degree media, browser companion experiences and reusable Three.js presentation modules.',
    'Strong partnership prospect because Ideum combines hardware, exhibit fabrication and custom software. Position IOM as a source of focused 3D, spatial and browser-based production that can fit into Ideum''s larger installations. Liz Richardson is publicly listed as Director of Sales & Marketing. Use the official sales address. Sources: https://ideum.com/team, https://ideum.com/contact, https://ideum.com/about',
    'Interactive design and technology company producing multitouch tables, kiosks, custom software, exhibits, fabrication, projection-mapped experiences and integrated hardware and software for museums and public spaces.',
    '3D and spatial-production support for Ideum',
    'Hi Liz,

I recently explored Ideum''s work across interactive exhibits, multitouch systems, custom software and integrated public-space experiences, and I wanted to introduce IOM — Interactive Object Media.

IOM is a small creative and technical studio focused on interactive 3D, browser-based experiences, photogrammetry, architectural visualization, 360-degree environments and optimized real-time asset production.

My work includes creating and optimizing complex 3D environments, reconstructing objects and spaces from photography or architectural files, building interactive Three.js presentations and developing custom tools for exploring 3D content. I also develop the IOM 3D Viewer for browser and desktop model presentation.

Ideum already brings together software, hardware and fabrication, so I am not proposing a competing service. I thought IOM could be useful as an external specialist when a project requires additional capacity for 3D content, virtual reconstruction, spatial capture, optimized models, a 360-degree environment or a browser-based companion experience.

You can see an overview of my work at:
https://iobjectm.com/

I would be glad to send a short selection of relevant examples and learn whether Ideum works with independent 3D and interactive-production partners.

Would you be open to a brief introductory conversation?

Best regards,

Mirjan Čubrić
IOM — Interactive Object Media
https://iobjectm.com/
iom-production@proton.me',
    null::timestamptz,
    null::timestamptz,
    'warm',
    'new',
    null::date,
    null::numeric,
    '🤝',
    '2469 Corrales Road, Building C, Corrales, NM 87048, United States',
    'America/Denver',
    'Corrales',
    'United States',
    null::double precision,
    null::double precision
  ),
  (
    'Cortina Productions',
    'https://www.cortinaproductions.com/',
    '[{"label":"Jim Cortina","url":"https://www.cortinaproductions.com/people/jim-cortina/"},{"label":"Team","url":"https://www.cortinaproductions.com/people/"},{"label":"Contact","url":"https://www.cortinaproductions.com/contact/"},{"label":"Projects","url":"https://www.cortinaproductions.com/projects/"}]'::jsonb,
    'Jim Cortina',
    'Media Designer, Founding Member',
    'hello@cortinaproductions.com',
    '+1 703 556 8481',
    'Specialized 3D and spatial-production support for museum films, interactives and visitor experiences. IOM can provide virtual reconstructions, architectural environments, photogrammetry, optimized real-time models, 360-degree capture and post-production, browser-based companion experiences and custom interactive model presentations.',
    'Strong museum-media partnership lead. Jim Cortina is a founding member and his current public profile says he supports business development, strategic partnerships and media planning. Contact him through the official hello address. IOM should be positioned as a specialist able to own 3D, spatial reconstruction, 360 or browser-based portions of larger museum projects. Sources: https://www.cortinaproductions.com/people/jim-cortina/, https://www.cortinaproductions.com/people/, https://www.cortinaproductions.com/contact/',
    'Museum-media production company creating films, animations, software, interactive exhibits, augmented-reality experiences, touch displays and custom visitor experiences for museums, sports venues and cultural institutions.',
    '3D and spatial support for museum-media projects',
    'Hi Jim,

I recently reviewed Cortina Productions'' museum-media and interactive work and wanted to introduce IOM — Interactive Object Media.

IOM is a small creative and technical studio working across interactive 3D, browser-based experiences, architectural visualization, photogrammetry, virtual reconstruction and 360-degree environments.

My background includes optimizing complex models for real-time use, developing Three.js experiences, reconstructing sites and objects from photographic or architectural material and building custom tools for presenting 3D content. I also develop the IOM 3D Viewer, a browser and desktop platform for interactive model presentation.

Cortina already has extensive internal expertise in film, animation, software and interactive design. I am therefore reaching out as a potential specialist or overflow production partner. IOM could support a larger museum project when it needs focused production for a historical environment, architectural model, photogrammetry asset, 360-degree component or browser-based companion experience.

An overview of my current work is available at:
https://iobjectm.com/

I would be happy to send a concise selection of relevant examples and learn how Cortina normally works with external production specialists.

Would you be open to a brief introduction?

Best regards,

Mirjan Čubrić
IOM — Interactive Object Media
https://iobjectm.com/
iom-production@proton.me',
    null::timestamptz,
    null::timestamptz,
    'warm',
    'new',
    null::date,
    null::numeric,
    '🤝',
    '1651 Old Meadow Road, Suite 400, McLean, VA 22102, United States',
    'America/New_York',
    'McLean',
    'United States',
    null::double precision,
    null::double precision
  ),
  (
    'Local Projects',
    'https://localprojects.com/',
    '[{"label":"People","url":"https://localprojects.com/people/"},{"label":"Contact","url":"https://localprojects.com/contact/"},{"label":"Work","url":"https://localprojects.com/work/"}]'::jsonb,
    'Alice Walker',
    'Executive Director, New Business and Marketing',
    'info@localprojects.com',
    '+1 212 480 0479',
    'External specialist support for exhibition and media projects involving virtual reconstruction, architectural visualization, optimized real-time environments, interactive browser-based 3D, photogrammetry, 360-degree spatial documentation and custom presentation modules.',
    'High-value but competitive partnership target. Alice Walker is publicly listed as Executive Director of New Business and Marketing and oversees business development for the studio. Present IOM as focused production capacity that can integrate into Local Projects'' multidisciplinary teams. Avoid presenting general exhibit-design services. Sources: https://localprojects.com/people/, https://localprojects.com/contact/, https://localprojects.com/',
    'Experience and exhibition-design firm creating museum, civic, cultural and brand experiences through physical design, interactive media, software, content strategy, storytelling and emerging technology.',
    'Specialist 3D production for Local Projects',
    'Hi Alice,

I recently spent time exploring Local Projects'' exhibition, museum and media work and wanted to introduce IOM — Interactive Object Media.

IOM is a small creative and technical studio focused on interactive 3D, browser-based real-time experiences, architectural visualization, photogrammetry, spatial reconstruction and 360-degree environments.

My work includes building and optimizing complex 3D spaces, reconstructing locations and objects from photographic or architectural data, creating Three.js experiences and developing custom tools for presenting interactive models. I also develop the IOM 3D Viewer for browser and desktop publishing.

Local Projects already covers the broader strategy, design and delivery of complex experiences, so I am not approaching you with an overlapping full-service offer. I thought IOM could be useful as external specialist capacity when a project needs focused production for a historical reconstruction, architectural environment, photogrammetry asset, web-based 3D module, virtual walkthrough or 360-degree spatial component.

You can see an overview of my work at:
https://iobjectm.com/

I would be happy to send a focused selection of examples and learn whether Local Projects works with independent 3D and technical-production partners.

Would you be open to a brief introductory conversation?

Best regards,

Mirjan Čubrić
IOM — Interactive Object Media
https://iobjectm.com/
iom-production@proton.me',
    null::timestamptz,
    null::timestamptz,
    'warm',
    'new',
    null::date,
    null::numeric,
    '🤝',
    '123 William Street, Suite 801, New York, NY 10038, United States',
    'America/New_York',
    'New York',
    'United States',
    null::double precision,
    null::double precision
  ),
  (
    'Unified Field',
    'https://www.unifiedfield.com/',
    '[{"label":"About and capabilities","url":"https://www.unifiedfield.com/about"},{"label":"Contact","url":"https://www.unifiedfield.com/contact"},{"label":"Work","url":"https://www.unifiedfield.com/"}]'::jsonb,
    'Eli Kuslansky',
    'Partner, Chief Strategist',
    'info@unifiedfield.com',
    '+1 212 532 9595',
    'Flexible 3D and real-time production support for Unified Field''s interactive and immersive projects. IOM can provide optimized environments, architectural and object reconstruction, photogrammetry, 360-degree media, WebGL/WebGPU prototypes, Three.js companion experiences and custom interactive 3D modules.',
    'Strong technical collaboration prospect. Unified Field offers many services overlapping with IOM, so the approach must focus on specialized 3D and spatial production rather than general experience design. Eli Kuslansky is publicly identified as Partner and Chief Strategist. Use the official general contact address. Sources: https://www.unifiedfield.com/about, https://www.unifiedfield.com/contact, https://cooper.edu/art/news/designing-breakthrough',
    'Creative innovation and media-production firm creating interactive and immersive experiences, personalized experiences, branded environments, media walls, digital signage, wayfinding, AR, VR, MR, websites, mobile applications, film, animation and software.',
    'Possible 3D and real-time production collaboration',
    'Hi Eli,

I recently explored Unified Field''s work across interactive media, immersive environments, spatial storytelling and emerging technology, and I wanted to introduce IOM — Interactive Object Media.

IOM is a small creative and technical studio focused on real-time 3D, browser-based Three.js experiences, WebGL and WebGPU development, photogrammetry, architectural visualization and 360-degree environments.

My work includes preparing complex models for real-time delivery, producing interactive spatial environments, reconstructing spaces and objects and building custom tools for browser and desktop 3D presentation. I also develop the IOM 3D Viewer, which supports interactive model presentation and standalone web publishing.

Because Unified Field already has broad interactive-design and production capabilities, I am reaching out as a potential specialist collaborator rather than with a competing agency offer. IOM could support your team when a project needs additional capacity for a 3D environment, photogrammetry asset, architectural reconstruction, browser-based spatial module, WebGL prototype or 360-degree component.

An overview of my current work is available at:
https://iobjectm.com/

I would be glad to exchange work and learn how Unified Field normally collaborates with independent technical specialists.

Would you be open to a short introduction?

Best regards,

Mirjan Čubrić
IOM — Interactive Object Media
https://iobjectm.com/
iom-production@proton.me',
    null::timestamptz,
    null::timestamptz,
    'warm',
    'new',
    null::date,
    null::numeric,
    '🤝',
    '406 Waverly Avenue, Brooklyn, NY 11238, United States',
    'America/New_York',
    'Brooklyn',
    'United States',
    null::double precision,
    null::double precision
  ),
  (
    'RLMG',
    'https://www.rlmg.com/',
    '[{"label":"Team","url":"https://www.rlmg.com/team"},{"label":"Contact","url":"https://www.rlmg.com/contact"},{"label":"Work","url":"https://www.rlmg.com/work"}]'::jsonb,
    'Sara Smith',
    'Head of Partnerships',
    'hello@rlmg.com',
    '',
    'Specialized 3D, photogrammetry and spatial-production support for RLMG''s museum and public-space installations. IOM can create optimized scientific or historical models, virtual environments, architectural reconstructions, interactive Three.js components, 360-degree media and browser-based extensions of physical exhibits.',
    'High-priority museum and immersive-media partnership. RLMG already produces software, animation, projection mapping, interactive media and immersive environments. Position IOM as a focused 3D, spatial-reconstruction and browser-production specialist. Sara Smith is publicly listed as Head of Partnerships. Sources: https://www.rlmg.com/team, https://www.rlmg.com/contact, https://www.rlmg.com/',
    'Employee-owned digital-experience design studio creating story-driven interactive, immersive, dynamic and educational installations for museums, public spaces, universities, visitor centers and brands.',
    '3D and spatial-production support for RLMG',
    'Hi Sara,

I recently explored RLMG''s museum and public-space work, particularly the way your projects combine software, animation, projection, interactive media and immersive environments.

I run IOM — Interactive Object Media, a small creative and technical studio focused on interactive 3D, browser-based experiences, photogrammetry, architectural visualization, spatial reconstruction and 360-degree environments.

My work includes producing and optimizing real-time models, reconstructing spaces and objects from photography or architectural information, creating Three.js experiences and developing custom tools for interactive model presentation. I also develop the IOM 3D Viewer for browser and desktop use.

I thought IOM could be useful as an external production partner when an RLMG project requires additional capacity for a scientific or historical 3D environment, photogrammetry asset, architectural reconstruction, browser-based exhibit extension or 360-degree spatial component.

The intention would be to support RLMG''s concept and creative direction while taking ownership of focused technical and production-heavy deliverables.

You can see an overview of my current work at:
https://iobjectm.com/

I would be happy to send a small selection of relevant examples. Would you be open to a brief introductory conversation?

Best regards,

Mirjan Čubrić
IOM — Interactive Object Media
https://iobjectm.com/
iom-production@proton.me',
    null::timestamptz,
    null::timestamptz,
    'warm',
    'new',
    null::date,
    null::numeric,
    '🤝',
    '70 Coolidge Hill Road, Watertown, MA 02472, United States',
    'America/New_York',
    'Watertown',
    'United States',
    null::double precision,
    null::double precision
  ),
  (
    'Trivium Interactive',
    'https://www.triviuminteractive.com/',
    '[{"label":"Team","url":"https://www.triviuminteractive.com/our-team"},{"label":"Contact","url":"https://www.triviuminteractive.com/contact-us"},{"label":"Work","url":"https://www.triviuminteractive.com/our-work"}]'::jsonb,
    'Lani Wyman',
    'Manager of Business Development',
    'info@triviuminteractive.com',
    '',
    'External 3D and browser-production support for Trivium''s museum, visitor-center and attraction projects. IOM can provide virtual reconstruction, optimized real-time models, photogrammetry, architectural visualization, interactive Three.js environments, 360-degree experiences and custom web-based presentation modules.',
    'Strong fit because Trivium produces full-stack programming, experiential media, animation, prototyping and interactive museum installations. Lani Wyman is publicly listed as Manager of Business Development and seeks new opportunities and partnerships. Position IOM as additional capacity for focused 3D, spatial and browser modules. Sources: https://www.triviuminteractive.com/our-team, https://www.triviuminteractive.com/, https://www.triviuminteractive.com/contact-us',
    'Women-owned multimedia design and production studio creating interactive and immersive media for museums, visitor centers, zoos, aquariums, cultural institutions, corporations and attractions.',
    '3D production support for Trivium''s interactive projects',
    'Hi Lani,

I recently explored Trivium''s museum and visitor-experience work and wanted to introduce IOM — Interactive Object Media.

IOM is a small creative and technical studio focused on interactive 3D, browser-based Three.js experiences, architectural visualization, photogrammetry, virtual reconstruction and 360-degree environments.

My work includes producing optimized real-time assets, reconstructing spaces and objects from photography or architectural files, building interactive web environments and developing custom tools for presenting 3D content. I also develop the IOM 3D Viewer for browser and desktop use.

Trivium already has a multidisciplinary team covering design, content, production and software. I am therefore approaching you as a potential specialist or overflow collaborator. IOM could support a larger project when it needs focused production for a virtual environment, historical or scientific reconstruction, architectural model, photogrammetry asset, 360-degree component or browser-based 3D experience.

You can see an overview of my current work at:
https://iobjectm.com/

I would be happy to send a focused selection of relevant examples and learn how Trivium normally works with external production partners.

Would you be open to a brief introduction?

Best regards,

Mirjan Čubrić
IOM — Interactive Object Media
https://iobjectm.com/
iom-production@proton.me',
    null::timestamptz,
    null::timestamptz,
    'warm',
    'new',
    null::date,
    null::numeric,
    '🤝',
    '137 Portland Street, 4th Floor, Boston, MA 02114, United States',
    'America/New_York',
    'Boston',
    'United States',
    null::double precision,
    null::double precision
  ),
  (
    'Luci',
    'https://www.lucicreative.com/',
    '[{"label":"Team","url":"https://www.lucicreative.com/team"},{"label":"Projects","url":"https://www.lucicreative.com/projects"},{"label":"Contact","url":"https://www.lucicreative.com/contact"},{"label":"LinkedIn","url":"https://www.linkedin.com/company/luci-creative"}]'::jsonb,
    'Amy Bornkamp',
    'Strategic Partnerships',
    'hello@lucicreative.com',
    '',
    'Technical and 3D production support for Luci''s museum, cultural and brand experiences. IOM can contribute interactive environments, architectural visualization, virtual reconstruction, photogrammetry, optimized browser-based 3D, 360-degree media and custom software modules within Luci''s overall exhibit concept and design.',
    'High-priority exhibit-design partnership prospect. Luci focuses on broader experience strategy and physical exhibit design, making specialist digital and 3D production a complementary offer. Amy Bornkamp is listed under Strategic Partnerships. Use the official general contact email and address the message to Amy. Sources: https://www.lucicreative.com/team, https://www.lucicreative.com/, https://www.linkedin.com/company/luci-creative',
    'Experience-design studio creating museum and brand environments, exhibitions, interactive experiences and emotionally engaging spaces for cultural institutions, corporations and public audiences.',
    'Technical 3D support for Luci experiences',
    'Hi Amy,

I recently explored Luci''s museum and brand-experience work and wanted to introduce IOM — Interactive Object Media.

IOM is a small creative and technical studio focused on interactive 3D, browser-based experiences, architectural visualization, photogrammetry, virtual reconstruction and 360-degree environments.

My work includes developing optimized real-time spaces, reconstructing locations and objects from photographic or architectural material, creating Three.js experiences and building custom tools for interactive model presentation. I also develop the IOM 3D Viewer for browser and desktop publishing.

Luci''s work is broader than the technical services I provide, which is why I see the strongest possibility as a production partnership. IOM could support your creative and project teams when an experience needs a virtual environment, architectural visualization, historical reconstruction, photogrammetry asset, browser-based 3D component or 360-degree spatial experience.

I would work within Luci''s concept and creative direction while taking responsibility for focused technical or production-heavy deliverables.

An overview of my work is available at:
https://iobjectm.com/

I would be glad to send a short selection of relevant examples and learn how Luci collaborates with external media and technical partners.

Would you be open to a brief introductory conversation?

Best regards,

Mirjan Čubrić
IOM — Interactive Object Media
https://iobjectm.com/
iom-production@proton.me',
    null::timestamptz,
    null::timestamptz,
    'warm',
    'new',
    null::date,
    null::numeric,
    '🤝',
    '6950 N Central Park Avenue, Lincolnwood, IL 60712, United States',
    'America/Chicago',
    'Lincolnwood',
    'United States',
    null::double precision,
    null::double precision
  ),
  (
    'Hyperquake',
    'https://www.hyperquake.com/',
    '[{"label":"Team and capabilities","url":"https://www.hyperquake.com/about-us"},{"label":"Contact","url":"https://www.hyperquake.com/contact"},{"label":"Experience work","url":"https://www.hyperquake.com/services/experiences"}]'::jsonb,
    'Marshall Thompson',
    'Executive Director, Experiences',
    'hello@hyperquake.com',
    '+1 513 563 6555',
    'Specialist real-time 3D and technical production for Hyperquake''s immersive brand environments and experience centers. IOM can provide optimized models, browser-based Three.js modules, architectural visualization, photogrammetry, virtual environments, interactive model presentations, 360-degree media and rapid WebGL/WebGPU prototypes.',
    'Strong but competitive agency-partnership prospect. Hyperquake has an established Experiences team, so IOM should be positioned as flexible capacity for project-specific 3D, environment and browser work. Marshall Thompson is publicly listed as Executive Director, Experiences and is based in Brooklyn. Use the official general collaboration email. Sources: https://www.hyperquake.com/about-us, https://www.hyperquake.com/contact, https://www.hyperquake.com/',
    'Independent strategy, brand and experience-design agency creating immersive brand experiences, customer and executive experience centers, interactive environments, campaigns and strategic design programs.',
    'Real-time 3D support for Hyperquake experiences',
    'Hi Marshall,

I recently explored Hyperquake''s immersive experience and brand-environment work and wanted to introduce IOM — Interactive Object Media.

IOM is a small creative and technical studio focused on real-time 3D, browser-based Three.js experiences, architectural visualization, photogrammetry, 360-degree environments and custom interactive presentation tools.

My work includes preparing complex models for real-time delivery, developing interactive spaces, creating rapid WebGL and WebGPU prototypes and building tools for exploring 3D content in browsers and standalone applications. I also develop the IOM 3D Viewer for interactive model presentation and web publishing.

Hyperquake already has a substantial Experiences team, so I am approaching you as a potential specialist or overflow collaborator rather than with a competing full-service offer. IOM could support a project when it needs additional capacity for an architectural environment, optimized 3D pipeline, browser-based interactive module, virtual reconstruction, 360-degree experience or rapid technical prototype.

You can see an overview of my current work at:
https://iobjectm.com/

I would be happy to send a focused selection of relevant examples and learn how Hyperquake works with external technical-production partners.

Would you be open to a brief introductory conversation?

Best regards,

Mirjan Čubrić
IOM — Interactive Object Media
https://iobjectm.com/
iom-production@proton.me',
    null::timestamptz,
    null::timestamptz,
    'warm',
    'new',
    null::date,
    null::numeric,
    '🤝',
    '',
    'America/New_York',
    'Brooklyn',
    'United States',
    null::double precision,
    null::double precision
  )
  ) as v (
    company_name, website, links, contact_name, contact_role, email, phone,
    offer, notes, company_focus, initial_email_subject, initial_email_body,
    initial_email_drafted_at, initial_email_sent_at, temperature, status,
    next_follow_up, estimated_value, value_emoji, client_address,
    client_timezone, client_city, client_country, client_lat, client_lon
  )
),
norm as (
  select
    i.*,
    lower(regexp_replace(
      regexp_replace(
        regexp_replace(trim(i.website), '^https?://', '', 'i'),
        '^www\.', '', 'i'
      ),
      '/+$', ''
    )) as website_domain,
    lower(trim(i.company_name)) as company_key
  from incoming i
),
existing as (
  select
    id,
    company_name,
    website,
    lower(regexp_replace(
      regexp_replace(
        regexp_replace(trim(website), '^https?://', '', 'i'),
        '^www\.', '', 'i'
      ),
      '/+$', ''
    )) as website_domain,
    lower(trim(company_name)) as company_key
  from public.crm_leads
),
to_insert as (
  select n.*
  from norm n
  where not exists (
    select 1 from existing e
    where e.website_domain <> ''
      and n.website_domain <> ''
      and e.website_domain = n.website_domain
  )
  and not exists (
    select 1 from existing e
    where e.company_key = n.company_key
  )
)
insert into public.crm_leads (
  company_name,
  website,
  links,
  contact_name,
  contact_role,
  email,
  phone,
  offer,
  notes,
  company_focus,
  initial_email_subject,
  initial_email_body,
  initial_email_drafted_at,
  initial_email_sent_at,
  temperature,
  status,
  next_follow_up,
  estimated_value,
  value_emoji,
  client_address,
  client_timezone,
  client_city,
  client_country,
  client_lat,
  client_lon,
  owner_id,
  owner_email,
  owner_avatar_url
)
select
  t.company_name,
  t.website,
  t.links,
  t.contact_name,
  t.contact_role,
  t.email,
  t.phone,
  t.offer,
  t.notes,
  t.company_focus,
  t.initial_email_subject,
  t.initial_email_body,
  t.initial_email_drafted_at,
  t.initial_email_sent_at,
  t.temperature,
  t.status,
  t.next_follow_up,
  t.estimated_value,
  t.value_emoji,
  t.client_address,
  t.client_timezone,
  t.client_city,
  t.client_country,
  t.client_lat,
  t.client_lon,
  m.id,
  m.email,
  m.avatar_url
from to_insert t
left join mirjan m on true
returning
  company_name,
  website,
  owner_email,
  status,
  temperature,
  value_emoji,
  (initial_email_subject <> '') as has_subject,
  (initial_email_body <> '') as has_body,
  initial_email_sent_at;

-- 2) Outcome report
with mirjan_check as (
  select count(*)::int as n
  from auth.users
  where email ilike '%mirjan%'
    and id <> '1dd6199e-25b2-4def-b790-7ce6a372ae53'::uuid
),
incoming as (
  select * from (values
  (
    'Bluecadet',
    'https://www.bluecadet.com/',
    '[{"label":"About and leadership","url":"https://www.bluecadet.com/about"},{"label":"Contact","url":"https://www.bluecadet.com/contact"},{"label":"LinkedIn","url":"https://www.linkedin.com/company/bluecadet-interactive"}]'::jsonb,
    'Rob Hassler',
    'Director of Strategic Partnerships',
    'info@bluecadet.com',
    '',
    'Specialist and overflow 3D production for Bluecadet''s museum, cultural and visitor-experience projects. IOM can support projects with optimized real-time models, interactive Three.js environments, architectural visualization, photogrammetry, virtual reconstruction, 360-degree media, browser-based 3D modules and custom presentation tools.',
    'High-priority partnership prospect. Bluecadet already has strong design and technology capabilities, so the offer should focus on specialized production capacity rather than general experience design. Rob Hassler is currently listed by Bluecadet as Director of Strategic Partnerships. The public general inquiry email should be used because no verified direct public work email was found. Sources: https://www.bluecadet.com/about, https://www.bluecadet.com/contact, https://www.linkedin.com/company/bluecadet-interactive',
    'Experience-design studio combining design, technology and storytelling for museums, cultural institutions, universities, mission-driven organizations and brands. Its work spans interactive media, digital products, websites and experiences in physical spaces.',
    'Specialist 3D support for Bluecadet projects',
    'Hi Rob,

I recently spent some time looking through Bluecadet''s museum, cultural and interactive work and wanted to introduce IOM — Interactive Object Media.

IOM is a small creative and technical studio focused on interactive 3D software, browser-based Three.js experiences, optimized real-time environments, architectural visualization, photogrammetry and 360-degree virtual experiences.

My work includes preparing complex models for browser delivery, creating interactive environments, reconstructing spaces from photographic or architectural material and developing custom tools for presenting 3D content. I also develop the IOM 3D Viewer, a browser and desktop platform for publishing and exploring optimized models.

I am approaching Bluecadet as a potential specialist production partner rather than as a competing experience-design studio. IOM could support your team when a project needs additional capacity for a 3D environment, virtual reconstruction, architectural model, photogrammetry component, 360-degree experience or technically demanding browser-based module.

An overview of my current work is available at:
https://iobjectm.com/

I would be happy to send a focused selection of relevant examples and learn how Bluecadet normally collaborates with independent technical specialists.

Would you be open to a brief introductory conversation?

Best regards,

Mirjan Čubrić
IOM — Interactive Object Media
https://iobjectm.com/
iom-production@proton.me',
    null::timestamptz,
    null::timestamptz,
    'warm',
    'new',
    null::date,
    null::numeric,
    '🤝',
    '1526 Frankford Avenue, Philadelphia, PA 19125, United States',
    'America/New_York',
    'Philadelphia',
    'United States',
    null::double precision,
    null::double precision
  ),
  (
    'Ideum',
    'https://ideum.com/',
    '[{"label":"Team","url":"https://ideum.com/team"},{"label":"Contact and sales","url":"https://ideum.com/contact"},{"label":"Capabilities","url":"https://ideum.com/capabilities"}]'::jsonb,
    'Liz Richardson',
    'Director of Sales & Marketing',
    'sales@ideum.com',
    '+1 505 792 1110 ext. 1',
    'External production support for Ideum''s exhibits, touch displays and public-space installations. IOM can provide optimized 3D assets, interactive spatial environments, photogrammetry, object and site reconstruction, architectural visualization, 360-degree media, browser companion experiences and reusable Three.js presentation modules.',
    'Strong partnership prospect because Ideum combines hardware, exhibit fabrication and custom software. Position IOM as a source of focused 3D, spatial and browser-based production that can fit into Ideum''s larger installations. Liz Richardson is publicly listed as Director of Sales & Marketing. Use the official sales address. Sources: https://ideum.com/team, https://ideum.com/contact, https://ideum.com/about',
    'Interactive design and technology company producing multitouch tables, kiosks, custom software, exhibits, fabrication, projection-mapped experiences and integrated hardware and software for museums and public spaces.',
    '3D and spatial-production support for Ideum',
    'Hi Liz,

I recently explored Ideum''s work across interactive exhibits, multitouch systems, custom software and integrated public-space experiences, and I wanted to introduce IOM — Interactive Object Media.

IOM is a small creative and technical studio focused on interactive 3D, browser-based experiences, photogrammetry, architectural visualization, 360-degree environments and optimized real-time asset production.

My work includes creating and optimizing complex 3D environments, reconstructing objects and spaces from photography or architectural files, building interactive Three.js presentations and developing custom tools for exploring 3D content. I also develop the IOM 3D Viewer for browser and desktop model presentation.

Ideum already brings together software, hardware and fabrication, so I am not proposing a competing service. I thought IOM could be useful as an external specialist when a project requires additional capacity for 3D content, virtual reconstruction, spatial capture, optimized models, a 360-degree environment or a browser-based companion experience.

You can see an overview of my work at:
https://iobjectm.com/

I would be glad to send a short selection of relevant examples and learn whether Ideum works with independent 3D and interactive-production partners.

Would you be open to a brief introductory conversation?

Best regards,

Mirjan Čubrić
IOM — Interactive Object Media
https://iobjectm.com/
iom-production@proton.me',
    null::timestamptz,
    null::timestamptz,
    'warm',
    'new',
    null::date,
    null::numeric,
    '🤝',
    '2469 Corrales Road, Building C, Corrales, NM 87048, United States',
    'America/Denver',
    'Corrales',
    'United States',
    null::double precision,
    null::double precision
  ),
  (
    'Cortina Productions',
    'https://www.cortinaproductions.com/',
    '[{"label":"Jim Cortina","url":"https://www.cortinaproductions.com/people/jim-cortina/"},{"label":"Team","url":"https://www.cortinaproductions.com/people/"},{"label":"Contact","url":"https://www.cortinaproductions.com/contact/"},{"label":"Projects","url":"https://www.cortinaproductions.com/projects/"}]'::jsonb,
    'Jim Cortina',
    'Media Designer, Founding Member',
    'hello@cortinaproductions.com',
    '+1 703 556 8481',
    'Specialized 3D and spatial-production support for museum films, interactives and visitor experiences. IOM can provide virtual reconstructions, architectural environments, photogrammetry, optimized real-time models, 360-degree capture and post-production, browser-based companion experiences and custom interactive model presentations.',
    'Strong museum-media partnership lead. Jim Cortina is a founding member and his current public profile says he supports business development, strategic partnerships and media planning. Contact him through the official hello address. IOM should be positioned as a specialist able to own 3D, spatial reconstruction, 360 or browser-based portions of larger museum projects. Sources: https://www.cortinaproductions.com/people/jim-cortina/, https://www.cortinaproductions.com/people/, https://www.cortinaproductions.com/contact/',
    'Museum-media production company creating films, animations, software, interactive exhibits, augmented-reality experiences, touch displays and custom visitor experiences for museums, sports venues and cultural institutions.',
    '3D and spatial support for museum-media projects',
    'Hi Jim,

I recently reviewed Cortina Productions'' museum-media and interactive work and wanted to introduce IOM — Interactive Object Media.

IOM is a small creative and technical studio working across interactive 3D, browser-based experiences, architectural visualization, photogrammetry, virtual reconstruction and 360-degree environments.

My background includes optimizing complex models for real-time use, developing Three.js experiences, reconstructing sites and objects from photographic or architectural material and building custom tools for presenting 3D content. I also develop the IOM 3D Viewer, a browser and desktop platform for interactive model presentation.

Cortina already has extensive internal expertise in film, animation, software and interactive design. I am therefore reaching out as a potential specialist or overflow production partner. IOM could support a larger museum project when it needs focused production for a historical environment, architectural model, photogrammetry asset, 360-degree component or browser-based companion experience.

An overview of my current work is available at:
https://iobjectm.com/

I would be happy to send a concise selection of relevant examples and learn how Cortina normally works with external production specialists.

Would you be open to a brief introduction?

Best regards,

Mirjan Čubrić
IOM — Interactive Object Media
https://iobjectm.com/
iom-production@proton.me',
    null::timestamptz,
    null::timestamptz,
    'warm',
    'new',
    null::date,
    null::numeric,
    '🤝',
    '1651 Old Meadow Road, Suite 400, McLean, VA 22102, United States',
    'America/New_York',
    'McLean',
    'United States',
    null::double precision,
    null::double precision
  ),
  (
    'Local Projects',
    'https://localprojects.com/',
    '[{"label":"People","url":"https://localprojects.com/people/"},{"label":"Contact","url":"https://localprojects.com/contact/"},{"label":"Work","url":"https://localprojects.com/work/"}]'::jsonb,
    'Alice Walker',
    'Executive Director, New Business and Marketing',
    'info@localprojects.com',
    '+1 212 480 0479',
    'External specialist support for exhibition and media projects involving virtual reconstruction, architectural visualization, optimized real-time environments, interactive browser-based 3D, photogrammetry, 360-degree spatial documentation and custom presentation modules.',
    'High-value but competitive partnership target. Alice Walker is publicly listed as Executive Director of New Business and Marketing and oversees business development for the studio. Present IOM as focused production capacity that can integrate into Local Projects'' multidisciplinary teams. Avoid presenting general exhibit-design services. Sources: https://localprojects.com/people/, https://localprojects.com/contact/, https://localprojects.com/',
    'Experience and exhibition-design firm creating museum, civic, cultural and brand experiences through physical design, interactive media, software, content strategy, storytelling and emerging technology.',
    'Specialist 3D production for Local Projects',
    'Hi Alice,

I recently spent time exploring Local Projects'' exhibition, museum and media work and wanted to introduce IOM — Interactive Object Media.

IOM is a small creative and technical studio focused on interactive 3D, browser-based real-time experiences, architectural visualization, photogrammetry, spatial reconstruction and 360-degree environments.

My work includes building and optimizing complex 3D spaces, reconstructing locations and objects from photographic or architectural data, creating Three.js experiences and developing custom tools for presenting interactive models. I also develop the IOM 3D Viewer for browser and desktop publishing.

Local Projects already covers the broader strategy, design and delivery of complex experiences, so I am not approaching you with an overlapping full-service offer. I thought IOM could be useful as external specialist capacity when a project needs focused production for a historical reconstruction, architectural environment, photogrammetry asset, web-based 3D module, virtual walkthrough or 360-degree spatial component.

You can see an overview of my work at:
https://iobjectm.com/

I would be happy to send a focused selection of examples and learn whether Local Projects works with independent 3D and technical-production partners.

Would you be open to a brief introductory conversation?

Best regards,

Mirjan Čubrić
IOM — Interactive Object Media
https://iobjectm.com/
iom-production@proton.me',
    null::timestamptz,
    null::timestamptz,
    'warm',
    'new',
    null::date,
    null::numeric,
    '🤝',
    '123 William Street, Suite 801, New York, NY 10038, United States',
    'America/New_York',
    'New York',
    'United States',
    null::double precision,
    null::double precision
  ),
  (
    'Unified Field',
    'https://www.unifiedfield.com/',
    '[{"label":"About and capabilities","url":"https://www.unifiedfield.com/about"},{"label":"Contact","url":"https://www.unifiedfield.com/contact"},{"label":"Work","url":"https://www.unifiedfield.com/"}]'::jsonb,
    'Eli Kuslansky',
    'Partner, Chief Strategist',
    'info@unifiedfield.com',
    '+1 212 532 9595',
    'Flexible 3D and real-time production support for Unified Field''s interactive and immersive projects. IOM can provide optimized environments, architectural and object reconstruction, photogrammetry, 360-degree media, WebGL/WebGPU prototypes, Three.js companion experiences and custom interactive 3D modules.',
    'Strong technical collaboration prospect. Unified Field offers many services overlapping with IOM, so the approach must focus on specialized 3D and spatial production rather than general experience design. Eli Kuslansky is publicly identified as Partner and Chief Strategist. Use the official general contact address. Sources: https://www.unifiedfield.com/about, https://www.unifiedfield.com/contact, https://cooper.edu/art/news/designing-breakthrough',
    'Creative innovation and media-production firm creating interactive and immersive experiences, personalized experiences, branded environments, media walls, digital signage, wayfinding, AR, VR, MR, websites, mobile applications, film, animation and software.',
    'Possible 3D and real-time production collaboration',
    'Hi Eli,

I recently explored Unified Field''s work across interactive media, immersive environments, spatial storytelling and emerging technology, and I wanted to introduce IOM — Interactive Object Media.

IOM is a small creative and technical studio focused on real-time 3D, browser-based Three.js experiences, WebGL and WebGPU development, photogrammetry, architectural visualization and 360-degree environments.

My work includes preparing complex models for real-time delivery, producing interactive spatial environments, reconstructing spaces and objects and building custom tools for browser and desktop 3D presentation. I also develop the IOM 3D Viewer, which supports interactive model presentation and standalone web publishing.

Because Unified Field already has broad interactive-design and production capabilities, I am reaching out as a potential specialist collaborator rather than with a competing agency offer. IOM could support your team when a project needs additional capacity for a 3D environment, photogrammetry asset, architectural reconstruction, browser-based spatial module, WebGL prototype or 360-degree component.

An overview of my current work is available at:
https://iobjectm.com/

I would be glad to exchange work and learn how Unified Field normally collaborates with independent technical specialists.

Would you be open to a short introduction?

Best regards,

Mirjan Čubrić
IOM — Interactive Object Media
https://iobjectm.com/
iom-production@proton.me',
    null::timestamptz,
    null::timestamptz,
    'warm',
    'new',
    null::date,
    null::numeric,
    '🤝',
    '406 Waverly Avenue, Brooklyn, NY 11238, United States',
    'America/New_York',
    'Brooklyn',
    'United States',
    null::double precision,
    null::double precision
  ),
  (
    'RLMG',
    'https://www.rlmg.com/',
    '[{"label":"Team","url":"https://www.rlmg.com/team"},{"label":"Contact","url":"https://www.rlmg.com/contact"},{"label":"Work","url":"https://www.rlmg.com/work"}]'::jsonb,
    'Sara Smith',
    'Head of Partnerships',
    'hello@rlmg.com',
    '',
    'Specialized 3D, photogrammetry and spatial-production support for RLMG''s museum and public-space installations. IOM can create optimized scientific or historical models, virtual environments, architectural reconstructions, interactive Three.js components, 360-degree media and browser-based extensions of physical exhibits.',
    'High-priority museum and immersive-media partnership. RLMG already produces software, animation, projection mapping, interactive media and immersive environments. Position IOM as a focused 3D, spatial-reconstruction and browser-production specialist. Sara Smith is publicly listed as Head of Partnerships. Sources: https://www.rlmg.com/team, https://www.rlmg.com/contact, https://www.rlmg.com/',
    'Employee-owned digital-experience design studio creating story-driven interactive, immersive, dynamic and educational installations for museums, public spaces, universities, visitor centers and brands.',
    '3D and spatial-production support for RLMG',
    'Hi Sara,

I recently explored RLMG''s museum and public-space work, particularly the way your projects combine software, animation, projection, interactive media and immersive environments.

I run IOM — Interactive Object Media, a small creative and technical studio focused on interactive 3D, browser-based experiences, photogrammetry, architectural visualization, spatial reconstruction and 360-degree environments.

My work includes producing and optimizing real-time models, reconstructing spaces and objects from photography or architectural information, creating Three.js experiences and developing custom tools for interactive model presentation. I also develop the IOM 3D Viewer for browser and desktop use.

I thought IOM could be useful as an external production partner when an RLMG project requires additional capacity for a scientific or historical 3D environment, photogrammetry asset, architectural reconstruction, browser-based exhibit extension or 360-degree spatial component.

The intention would be to support RLMG''s concept and creative direction while taking ownership of focused technical and production-heavy deliverables.

You can see an overview of my current work at:
https://iobjectm.com/

I would be happy to send a small selection of relevant examples. Would you be open to a brief introductory conversation?

Best regards,

Mirjan Čubrić
IOM — Interactive Object Media
https://iobjectm.com/
iom-production@proton.me',
    null::timestamptz,
    null::timestamptz,
    'warm',
    'new',
    null::date,
    null::numeric,
    '🤝',
    '70 Coolidge Hill Road, Watertown, MA 02472, United States',
    'America/New_York',
    'Watertown',
    'United States',
    null::double precision,
    null::double precision
  ),
  (
    'Trivium Interactive',
    'https://www.triviuminteractive.com/',
    '[{"label":"Team","url":"https://www.triviuminteractive.com/our-team"},{"label":"Contact","url":"https://www.triviuminteractive.com/contact-us"},{"label":"Work","url":"https://www.triviuminteractive.com/our-work"}]'::jsonb,
    'Lani Wyman',
    'Manager of Business Development',
    'info@triviuminteractive.com',
    '',
    'External 3D and browser-production support for Trivium''s museum, visitor-center and attraction projects. IOM can provide virtual reconstruction, optimized real-time models, photogrammetry, architectural visualization, interactive Three.js environments, 360-degree experiences and custom web-based presentation modules.',
    'Strong fit because Trivium produces full-stack programming, experiential media, animation, prototyping and interactive museum installations. Lani Wyman is publicly listed as Manager of Business Development and seeks new opportunities and partnerships. Position IOM as additional capacity for focused 3D, spatial and browser modules. Sources: https://www.triviuminteractive.com/our-team, https://www.triviuminteractive.com/, https://www.triviuminteractive.com/contact-us',
    'Women-owned multimedia design and production studio creating interactive and immersive media for museums, visitor centers, zoos, aquariums, cultural institutions, corporations and attractions.',
    '3D production support for Trivium''s interactive projects',
    'Hi Lani,

I recently explored Trivium''s museum and visitor-experience work and wanted to introduce IOM — Interactive Object Media.

IOM is a small creative and technical studio focused on interactive 3D, browser-based Three.js experiences, architectural visualization, photogrammetry, virtual reconstruction and 360-degree environments.

My work includes producing optimized real-time assets, reconstructing spaces and objects from photography or architectural files, building interactive web environments and developing custom tools for presenting 3D content. I also develop the IOM 3D Viewer for browser and desktop use.

Trivium already has a multidisciplinary team covering design, content, production and software. I am therefore approaching you as a potential specialist or overflow collaborator. IOM could support a larger project when it needs focused production for a virtual environment, historical or scientific reconstruction, architectural model, photogrammetry asset, 360-degree component or browser-based 3D experience.

You can see an overview of my current work at:
https://iobjectm.com/

I would be happy to send a focused selection of relevant examples and learn how Trivium normally works with external production partners.

Would you be open to a brief introduction?

Best regards,

Mirjan Čubrić
IOM — Interactive Object Media
https://iobjectm.com/
iom-production@proton.me',
    null::timestamptz,
    null::timestamptz,
    'warm',
    'new',
    null::date,
    null::numeric,
    '🤝',
    '137 Portland Street, 4th Floor, Boston, MA 02114, United States',
    'America/New_York',
    'Boston',
    'United States',
    null::double precision,
    null::double precision
  ),
  (
    'Luci',
    'https://www.lucicreative.com/',
    '[{"label":"Team","url":"https://www.lucicreative.com/team"},{"label":"Projects","url":"https://www.lucicreative.com/projects"},{"label":"Contact","url":"https://www.lucicreative.com/contact"},{"label":"LinkedIn","url":"https://www.linkedin.com/company/luci-creative"}]'::jsonb,
    'Amy Bornkamp',
    'Strategic Partnerships',
    'hello@lucicreative.com',
    '',
    'Technical and 3D production support for Luci''s museum, cultural and brand experiences. IOM can contribute interactive environments, architectural visualization, virtual reconstruction, photogrammetry, optimized browser-based 3D, 360-degree media and custom software modules within Luci''s overall exhibit concept and design.',
    'High-priority exhibit-design partnership prospect. Luci focuses on broader experience strategy and physical exhibit design, making specialist digital and 3D production a complementary offer. Amy Bornkamp is listed under Strategic Partnerships. Use the official general contact email and address the message to Amy. Sources: https://www.lucicreative.com/team, https://www.lucicreative.com/, https://www.linkedin.com/company/luci-creative',
    'Experience-design studio creating museum and brand environments, exhibitions, interactive experiences and emotionally engaging spaces for cultural institutions, corporations and public audiences.',
    'Technical 3D support for Luci experiences',
    'Hi Amy,

I recently explored Luci''s museum and brand-experience work and wanted to introduce IOM — Interactive Object Media.

IOM is a small creative and technical studio focused on interactive 3D, browser-based experiences, architectural visualization, photogrammetry, virtual reconstruction and 360-degree environments.

My work includes developing optimized real-time spaces, reconstructing locations and objects from photographic or architectural material, creating Three.js experiences and building custom tools for interactive model presentation. I also develop the IOM 3D Viewer for browser and desktop publishing.

Luci''s work is broader than the technical services I provide, which is why I see the strongest possibility as a production partnership. IOM could support your creative and project teams when an experience needs a virtual environment, architectural visualization, historical reconstruction, photogrammetry asset, browser-based 3D component or 360-degree spatial experience.

I would work within Luci''s concept and creative direction while taking responsibility for focused technical or production-heavy deliverables.

An overview of my work is available at:
https://iobjectm.com/

I would be glad to send a short selection of relevant examples and learn how Luci collaborates with external media and technical partners.

Would you be open to a brief introductory conversation?

Best regards,

Mirjan Čubrić
IOM — Interactive Object Media
https://iobjectm.com/
iom-production@proton.me',
    null::timestamptz,
    null::timestamptz,
    'warm',
    'new',
    null::date,
    null::numeric,
    '🤝',
    '6950 N Central Park Avenue, Lincolnwood, IL 60712, United States',
    'America/Chicago',
    'Lincolnwood',
    'United States',
    null::double precision,
    null::double precision
  ),
  (
    'Hyperquake',
    'https://www.hyperquake.com/',
    '[{"label":"Team and capabilities","url":"https://www.hyperquake.com/about-us"},{"label":"Contact","url":"https://www.hyperquake.com/contact"},{"label":"Experience work","url":"https://www.hyperquake.com/services/experiences"}]'::jsonb,
    'Marshall Thompson',
    'Executive Director, Experiences',
    'hello@hyperquake.com',
    '+1 513 563 6555',
    'Specialist real-time 3D and technical production for Hyperquake''s immersive brand environments and experience centers. IOM can provide optimized models, browser-based Three.js modules, architectural visualization, photogrammetry, virtual environments, interactive model presentations, 360-degree media and rapid WebGL/WebGPU prototypes.',
    'Strong but competitive agency-partnership prospect. Hyperquake has an established Experiences team, so IOM should be positioned as flexible capacity for project-specific 3D, environment and browser work. Marshall Thompson is publicly listed as Executive Director, Experiences and is based in Brooklyn. Use the official general collaboration email. Sources: https://www.hyperquake.com/about-us, https://www.hyperquake.com/contact, https://www.hyperquake.com/',
    'Independent strategy, brand and experience-design agency creating immersive brand experiences, customer and executive experience centers, interactive environments, campaigns and strategic design programs.',
    'Real-time 3D support for Hyperquake experiences',
    'Hi Marshall,

I recently explored Hyperquake''s immersive experience and brand-environment work and wanted to introduce IOM — Interactive Object Media.

IOM is a small creative and technical studio focused on real-time 3D, browser-based Three.js experiences, architectural visualization, photogrammetry, 360-degree environments and custom interactive presentation tools.

My work includes preparing complex models for real-time delivery, developing interactive spaces, creating rapid WebGL and WebGPU prototypes and building tools for exploring 3D content in browsers and standalone applications. I also develop the IOM 3D Viewer for interactive model presentation and web publishing.

Hyperquake already has a substantial Experiences team, so I am approaching you as a potential specialist or overflow collaborator rather than with a competing full-service offer. IOM could support a project when it needs additional capacity for an architectural environment, optimized 3D pipeline, browser-based interactive module, virtual reconstruction, 360-degree experience or rapid technical prototype.

You can see an overview of my current work at:
https://iobjectm.com/

I would be happy to send a focused selection of relevant examples and learn how Hyperquake works with external technical-production partners.

Would you be open to a brief introductory conversation?

Best regards,

Mirjan Čubrić
IOM — Interactive Object Media
https://iobjectm.com/
iom-production@proton.me',
    null::timestamptz,
    null::timestamptz,
    'warm',
    'new',
    null::date,
    null::numeric,
    '🤝',
    '',
    'America/New_York',
    'Brooklyn',
    'United States',
    null::double precision,
    null::double precision
  )
  ) as v (
    company_name, website, links, contact_name, contact_role, email, phone,
    offer, notes, company_focus, initial_email_subject, initial_email_body,
    initial_email_drafted_at, initial_email_sent_at, temperature, status,
    next_follow_up, estimated_value, value_emoji, client_address,
    client_timezone, client_city, client_country, client_lat, client_lon
  )
),
norm as (
  select
    i.company_name,
    i.website,
    lower(regexp_replace(
      regexp_replace(
        regexp_replace(trim(i.website), '^https?://', '', 'i'),
        '^www\.', '', 'i'
      ),
      '/+$', ''
    )) as website_domain,
    lower(trim(i.company_name)) as company_key
  from incoming i
)
select
  n.company_name,
  n.website,
  case
    when exists (
      select 1 from public.crm_leads e
      where lower(regexp_replace(
              regexp_replace(
                regexp_replace(trim(e.website), '^https?://', '', 'i'),
                '^www\.', '', 'i'
              ),
              '/+$', ''
            )) = n.website_domain
        and n.website_domain <> ''
    ) then 'present (domain match — inserted or prior duplicate skipped)'
    when exists (
      select 1 from public.crm_leads e
      where lower(trim(e.company_name)) = n.company_key
    ) then 'present (company_name match — inserted or prior duplicate skipped)'
    else 'MISSING — insert did not land'
  end as outcome,
  (select n from mirjan_check) as mirjan_users_found
from norm n
order by n.company_name;
