import type { Artist, PortfolioWork } from './types'
import { portfolioImage } from './types'

function works(
  slug: string,
  items: Omit<PortfolioWork, 'id' | 'imageUrl'>[],
): PortfolioWork[] {
  return items.map((item, i) => ({
    id: `${slug}-w${i + 1}`,
    imageUrl: portfolioImage(slug, i + 1),
    ...item,
  }))
}

/** Seeded demo artists so the globe looks alive before real submissions. */
export const SEED_ARTISTS: Artist[] = [
  {
    id: 'seed-mira-voss',
    slug: 'mira-voss',
    displayName: 'Mira Voss',
    email: 'mira@example.com',
    category: 'photographer',
    tags: ['portrait', 'film', 'analog', 'night', 'black-and-white'],
    bio: 'Berlin-based photographer working with analog film and long exposures.',
    links: { website: 'https://example.com/mira', instagram: 'https://instagram.com/' },
    city: 'Berlin',
    country: 'Germany',
    lat: 52.52,
    lon: 13.405,
    timezone: 'Europe/Berlin',
    avatarUrl: '',
    status: 'live',
    portfolio: works('mira-voss', [
      { title: 'Neon Afterimage', year: '2024', medium: '35mm film', caption: 'Kreuzberg, 2 a.m.' },
      { title: 'Studio Window', year: '2023', medium: 'Gelatin silver print', caption: 'Portrait series' },
      { title: 'River Fog', year: '2025', medium: 'Medium format', caption: 'Spree at dawn' },
      { title: 'Contact Sheet #18', year: '2024', medium: 'Analog contact', caption: 'Editing room' },
    ]),
  },
  {
    id: 'seed-kenji-aoki',
    slug: 'kenji-aoki',
    displayName: 'Kenji Aoki',
    email: 'kenji@example.com',
    category: 'installation',
    tags: ['light', 'site-specific', 'large-scale', 'minimal'],
    bio: 'Installations that turn architecture into soft, shifting color fields.',
    links: { portfolio: 'https://example.com/kenji' },
    city: 'Tokyo',
    country: 'Japan',
    lat: 35.6762,
    lon: 139.6503,
    timezone: 'Asia/Tokyo',
    avatarUrl: '',
    status: 'live',
    portfolio: works('kenji-aoki', [
      { title: 'Corridor Gradient', year: '2025', medium: 'LED + fog', caption: 'Warehouse Annex B' },
      { title: 'Soft Horizon', year: '2023', medium: 'Projected light', caption: 'Night walk' },
      { title: 'Threshold Blue', year: '2024', medium: 'Site installation', caption: 'Ginza pop-up' },
      { title: 'Pulse Field', year: '2022', medium: 'Kinetic light', caption: 'Museum atrium' },
    ]),
  },
  {
    id: 'seed-sofia-reyes',
    slug: 'sofia-reyes',
    displayName: 'Sofía Reyes',
    email: 'sofia@example.com',
    category: 'conceptual',
    tags: ['archive', 'memory', 'identity', 'collage'],
    bio: 'Conceptual work around family archives and disappearing languages.',
    links: { website: 'https://example.com/sofia' },
    city: 'Mexico City',
    country: 'Mexico',
    lat: 19.4326,
    lon: -99.1332,
    timezone: 'America/Mexico_City',
    avatarUrl: '',
    status: 'live',
    portfolio: works('sofia-reyes', [
      { title: 'Letters Never Sent', year: '2024', medium: 'Archival collage', caption: 'Family correspondence' },
      { title: 'Mother Tongue Map', year: '2023', medium: 'Ink on vellum', caption: 'Linguistic loss' },
      { title: 'Dust Index', year: '2025', medium: 'Found photographs', caption: 'Domestic archive' },
      { title: 'Echo Table', year: '2022', medium: 'Mixed media', caption: 'Installation view' },
    ]),
  },
  {
    id: 'seed-owen-blake',
    slug: 'owen-blake',
    displayName: 'Owen Blake',
    email: 'owen@example.com',
    category: 'photographer',
    tags: ['landscape', 'documentary', 'nature', 'color'],
    bio: 'Documents coastal communities along the Pacific Northwest.',
    links: { instagram: 'https://instagram.com/' },
    city: 'Seattle',
    country: 'USA',
    lat: 47.6062,
    lon: -122.3321,
    timezone: 'America/Los_Angeles',
    avatarUrl: '',
    status: 'live',
    portfolio: works('owen-blake', [
      { title: 'Tide Line Crew', year: '2024', medium: 'Digital color', caption: 'Olympic Peninsula' },
      { title: 'Harbor Shift', year: '2023', medium: 'Documentary series', caption: 'Pier 7' },
      { title: 'Fog Net', year: '2025', medium: 'Large format', caption: 'Fishing nets at rest' },
      { title: 'Sunday Catch', year: '2022', medium: 'C-type print', caption: 'Market morning' },
    ]),
  },
  {
    id: 'seed-amira-hassan',
    slug: 'amira-hassan',
    displayName: 'Amira Hassan',
    email: 'amira@example.com',
    category: 'painter',
    tags: ['textile', 'abstract', 'urban', 'acrylic'],
    bio: 'Large-scale textile paintings drawing on Cairo street geometry.',
    links: { website: 'https://example.com/amira' },
    city: 'Cairo',
    country: 'Egypt',
    lat: 30.0444,
    lon: 31.2357,
    timezone: 'Africa/Cairo',
    avatarUrl: '',
    status: 'live',
    portfolio: works('amira-hassan', [
      { title: 'Lattice No. 4', year: '2025', medium: 'Acrylic on textile', caption: '2.4 × 3.1 m' },
      { title: 'Market Geometry', year: '2023', medium: 'Dyed cloth + paint', caption: 'Khan series' },
      { title: 'Heat Grid', year: '2024', medium: 'Mixed media', caption: 'Studio wall' },
      { title: 'Blue Passage', year: '2022', medium: 'Textile painting', caption: 'Public commission' },
    ]),
  },
  {
    id: 'seed-marko-vukovic',
    slug: 'marko-vukovic',
    displayName: 'Marko Vuković',
    email: 'marko@example.com',
    category: 'sound',
    tags: ['performance', 'sound', 'site-specific', 'field-recording', 'experimental'],
    bio: 'Sound performances staged in empty industrial halls across the Balkans.',
    links: { portfolio: 'https://example.com/marko' },
    city: 'Zagreb',
    country: 'Croatia',
    lat: 45.815,
    lon: 15.9819,
    timezone: 'Europe/Zagreb',
    avatarUrl: '',
    status: 'live',
    portfolio: works('marko-vukovic', [
      { title: 'Hall Resonance', year: '2024', medium: 'Live performance', caption: 'Former textile plant' },
      { title: 'Idle Machinery', year: '2023', medium: 'Field recording', caption: '60-minute loop' },
      { title: 'Audience as Score', year: '2025', medium: 'Participatory sound', caption: 'Night session' },
      { title: 'Steel Delay', year: '2022', medium: 'Installation + audio', caption: 'Documentation still' },
    ]),
  },
  {
    id: 'seed-nina-okoro',
    slug: 'nina-okoro',
    displayName: 'Nina Okoro',
    email: 'nina@example.com',
    category: 'photographer',
    tags: ['street', 'color', 'urban', 'documentary'],
    bio: 'Street color studies from Lagos markets and transit hubs.',
    links: { website: 'https://example.com/nina', instagram: 'https://instagram.com/' },
    city: 'Lagos',
    country: 'Nigeria',
    lat: 6.5244,
    lon: 3.3792,
    timezone: 'Africa/Lagos',
    avatarUrl: '',
    status: 'live',
    portfolio: works('nina-okoro', [
      { title: 'Yellow Bus Hour', year: '2025', medium: 'Digital street', caption: 'Oshodi interchange' },
      { title: 'Pepper Red', year: '2024', medium: 'Color study', caption: 'Market stall' },
      { title: 'Shade Line', year: '2023', medium: 'Candid series', caption: 'Midday heat' },
      { title: 'Transit Blues', year: '2022', medium: 'Inkjet print', caption: 'Ferry terminal' },
    ]),
  },
  {
    id: 'seed-elise-martin',
    slug: 'elise-martin',
    displayName: 'Élise Martin',
    email: 'elise@example.com',
    category: 'sculptor',
    tags: ['glass', 'light', 'minimal', 'figurative'],
    bio: 'Fragile glass sculptures that catch museum light like weather.',
    links: { website: 'https://example.com/elise' },
    city: 'Paris',
    country: 'France',
    lat: 48.8566,
    lon: 2.3522,
    timezone: 'Europe/Paris',
    avatarUrl: '',
    status: 'live',
    portfolio: works('elise-martin', [
      { title: 'Breath Vessel', year: '2025', medium: 'Blown glass', caption: 'Pedestal series' },
      { title: 'Fracture Soft', year: '2023', medium: 'Kiln-formed glass', caption: 'Wall piece' },
      { title: 'Clear Shadow', year: '2024', medium: 'Glass + steel', caption: 'Museum light study' },
      { title: 'Tide Form', year: '2022', medium: 'Cast glass', caption: 'Edition of 5' },
    ]),
  },
  {
    id: 'seed-jonas-berg',
    slug: 'jonas-berg',
    displayName: 'Jonas Berg',
    email: 'jonas@example.com',
    category: 'digital',
    tags: ['data', 'mapping', 'abstract', 'site-specific'],
    bio: 'Maps invisible climate data onto public plazas as temporary chalk works and screens.',
    links: { portfolio: 'https://example.com/jonas' },
    city: 'Stockholm',
    country: 'Sweden',
    lat: 59.3293,
    lon: 18.0686,
    timezone: 'Europe/Stockholm',
    avatarUrl: '',
    status: 'live',
    portfolio: works('jonas-berg', [
      { title: 'Heat Overlay', year: '2025', medium: 'Projection mapping', caption: 'Sergels torg' },
      { title: 'Chalk Forecast', year: '2024', medium: 'Public drawing + data', caption: '48-hour piece' },
      { title: 'Wind Glyphs', year: '2023', medium: 'Generative screen', caption: 'Gallery loop' },
      { title: 'Ice Index', year: '2022', medium: 'Interactive map', caption: 'Web commission' },
    ]),
  },
  {
    id: 'seed-priya-nair',
    slug: 'priya-nair',
    displayName: 'Priya Nair',
    email: 'priya@example.com',
    category: 'photographer',
    tags: ['architecture', 'minimal', 'light', 'black-and-white'],
    bio: 'Minimal architectural photography across South Indian temple towns.',
    links: { website: 'https://example.com/priya' },
    city: 'Bengaluru',
    country: 'India',
    lat: 12.9716,
    lon: 77.5946,
    timezone: 'Asia/Kolkata',
    avatarUrl: '',
    status: 'live',
    portfolio: works('priya-nair', [
      { title: 'Column Silence', year: '2024', medium: 'Large format B&W', caption: 'Temple corridor' },
      { title: 'Courtyard Noon', year: '2025', medium: 'Digital architecture', caption: 'Hard shadow study' },
      { title: 'Stepwell Line', year: '2023', medium: 'Inkjet print', caption: 'Geometry series' },
      { title: 'Threshold Dust', year: '2022', medium: 'Gelatin silver', caption: 'Doorway light' },
    ]),
  },
  {
    id: 'seed-marco-silva',
    slug: 'marco-silva',
    displayName: 'Marco Silva',
    email: 'marco@example.com',
    category: 'painter',
    tags: ['urban', 'figurative', 'large-scale', 'acrylic'],
    bio: 'Murals that braid local folklore into contemporary city walls.',
    links: { instagram: 'https://instagram.com/' },
    city: 'São Paulo',
    country: 'Brazil',
    lat: -23.5505,
    lon: -46.6333,
    timezone: 'America/Sao_Paulo',
    avatarUrl: '',
    status: 'live',
    portfolio: works('marco-silva', [
      { title: 'Folklore Wall', year: '2025', medium: 'Acrylic mural', caption: 'Vila Madalena' },
      { title: 'Night Parade', year: '2023', medium: 'Street painting', caption: 'Commission' },
      { title: 'River Myth', year: '2024', medium: 'Spray + brush', caption: '8 × 14 m' },
      { title: 'Studio Sketch 09', year: '2022', medium: 'Acrylic on panel', caption: 'Character study' },
    ]),
  },
  {
    id: 'seed-hana-lee',
    slug: 'hana-lee',
    displayName: 'Hana Lee',
    email: 'hana@example.com',
    category: 'filmmaker',
    tags: ['identity', 'memory', 'digital', 'performance'],
    bio: 'Video essays on diaspora identity and digital self-portraiture.',
    links: { website: 'https://example.com/hana' },
    city: 'Seoul',
    country: 'South Korea',
    lat: 37.5665,
    lon: 126.978,
    timezone: 'Asia/Seoul',
    avatarUrl: '',
    status: 'live',
    portfolio: works('hana-lee', [
      { title: 'Mirror Lag', year: '2025', medium: 'Single-channel video', caption: '12 min' },
      { title: 'Call Home Buffer', year: '2023', medium: 'Video essay', caption: 'Loop installation' },
      { title: 'Caption Self', year: '2024', medium: 'Digital collage film', caption: 'Festival cut' },
      { title: 'Still Frame 04', year: '2022', medium: 'Video still print', caption: 'Edition' },
    ]),
  },
  {
    id: 'seed-rafael-costa',
    slug: 'rafael-costa',
    displayName: 'Rafael Costa',
    email: 'rafael@example.com',
    category: 'illustrator',
    tags: ['figurative', 'watercolor', 'portrait', 'narrative'],
    bio: 'Narrative illustration and editorial drawing for books and magazines.',
    links: { website: 'https://example.com/rafael', portfolio: 'https://example.com/rafael/work' },
    city: 'Lisbon',
    country: 'Portugal',
    lat: 38.7223,
    lon: -9.1393,
    timezone: 'Europe/Lisbon',
    avatarUrl: '',
    status: 'live',
    portfolio: works('rafael-costa', [
      { title: 'Harbor Characters', year: '2025', medium: 'Ink + watercolor', caption: 'Book commission' },
      { title: 'Editorial Night', year: '2024', medium: 'Digital illustration', caption: 'Magazine cover' },
      { title: 'Sketchbook City', year: '2023', medium: 'Pencil on paper', caption: 'Travel pages' },
      { title: 'Quiet Portrait', year: '2022', medium: 'Gouache', caption: 'Private collection' },
    ]),
  },
  {
    id: 'seed-aya-morimoto',
    slug: 'aya-morimoto',
    displayName: 'Aya Morimoto',
    email: 'aya@example.com',
    category: 'sound',
    tags: ['electroacoustic', 'ambient', 'composition', 'experimental'],
    bio: 'Electroacoustic composer weaving city noise into slow, immersive listening pieces.',
    links: { website: 'https://example.com/aya', portfolio: 'https://example.com/aya/listen' },
    city: 'Osaka',
    country: 'Japan',
    lat: 34.6937,
    lon: 135.5023,
    timezone: 'Asia/Tokyo',
    avatarUrl: '',
    status: 'live',
    portfolio: works('aya-morimoto', [
      { title: 'Underpass Hum', year: '2025', medium: 'Fixed media', caption: '32-minute stereo' },
      { title: 'River Delay', year: '2024', medium: 'Live electronics', caption: 'Concert hall' },
      { title: 'Night Grid', year: '2023', medium: 'Ambisonic', caption: 'Dome commission' },
      { title: 'Soft Static', year: '2022', medium: 'Album / EP', caption: 'Listening room' },
    ]),
  },
  {
    id: 'seed-dariusz-kolek',
    slug: 'dariusz-kolek',
    displayName: 'Dariusz Kołek',
    email: 'dariusz@example.com',
    category: 'sound',
    tags: ['field-recording', 'noise', 'site-specific', 'archive'],
    bio: 'Documents industrial borderlands through long-form field recordings and noise scores.',
    links: { portfolio: 'https://example.com/dariusz' },
    city: 'Kraków',
    country: 'Poland',
    lat: 50.0647,
    lon: 19.945,
    timezone: 'Europe/Warsaw',
    avatarUrl: '',
    status: 'live',
    portfolio: works('dariusz-kolek', [
      { title: 'Factory Boundary', year: '2025', medium: 'Field recording', caption: 'Silesia line' },
      { title: 'Rail Bed', year: '2023', medium: 'Noise collage', caption: 'Night take' },
      { title: 'Ventilation Choir', year: '2024', medium: 'Multi-channel audio', caption: 'Gallery loop' },
      { title: 'Border Wind', year: '2022', medium: 'Stereo document', caption: 'Winter session' },
    ]),
  },
  {
    id: 'seed-zoe-bennett',
    slug: 'zoe-bennett',
    displayName: 'Zoe Bennett',
    email: 'zoe@example.com',
    category: 'sound',
    tags: ['sound', 'performance', 'ambient', 'light'],
    bio: 'Spatial sound and light performances for warehouses, chapels, and temporary rooms.',
    links: { website: 'https://example.com/zoe', instagram: 'https://instagram.com/' },
    city: 'Montreal',
    country: 'Canada',
    lat: 45.5017,
    lon: -73.5673,
    timezone: 'America/Toronto',
    avatarUrl: '',
    status: 'live',
    portfolio: works('zoe-bennett', [
      { title: 'Chapel Reverb', year: '2025', medium: 'Live spatial mix', caption: '60 min' },
      { title: 'Room Tone Ritual', year: '2024', medium: 'Performance', caption: 'Warehouse B' },
      { title: 'Pulse Lanterns', year: '2023', medium: 'Sound + light', caption: 'Festival night' },
      { title: 'Soft Threshold', year: '2022', medium: 'Quad installation', caption: 'Documentation' },
    ]),
  },
  {
    id: 'seed-ibrahim-diallo',
    slug: 'ibrahim-diallo',
    displayName: 'Ibrahim Diallo',
    email: 'ibrahim@example.com',
    category: 'sound',
    tags: ['composition', 'experimental', 'identity', 'digital'],
    bio: 'Builds hybrid scores from West African rhythms, synths, and spoken-word archives.',
    links: { website: 'https://example.com/ibrahim' },
    city: 'Dakar',
    country: 'Senegal',
    lat: 14.7167,
    lon: -17.4677,
    timezone: 'Africa/Dakar',
    avatarUrl: '',
    status: 'live',
    portfolio: works('ibrahim-diallo', [
      { title: 'Archive Pulse', year: '2025', medium: 'Hybrid score', caption: 'Radio commission' },
      { title: 'Market Syncopation', year: '2024', medium: 'Live set', caption: 'Club / gallery' },
      { title: 'Voice Maps', year: '2023', medium: 'Spoken + electronics', caption: 'Podcast series' },
      { title: 'Tide Drum', year: '2022', medium: 'Studio composition', caption: 'EP track' },
    ]),
  },
]
