import * as T from 'three'
export async function auditFeet(v:any,routes:any[],calibration:any,enabled:boolean){
 await v.character.load('/models/review-v4/Xbot-stairs-v4.glb');const a=v.character,c=v.controller,w=v.collision;a.setFootIKEnabled?.(enabled);a.setVisible(true);v.modelAnim.stop();w.setQueryLayer('icm-anim-2025');v.walk.activate(false);const results=[];
 const soleSets=calibration.feet.map((f:any)=>{const samples=[];for(const fx of [.15,.5,.85])for(const fz of [.12,.5,.88]){const x=T.MathUtils.lerp(f.bounds.min[0],f.bounds.max[0],fx),z=T.MathUtils.lerp(f.bounds.min[2],f.bounds.max[2],fz);let best=-1,score=Infinity;f.vertices.forEach((p:number[],i:number)=>{if(p[1]>f.bounds.min[1]+.018)return;const s=(p[0]-x)**2+(p[2]-z)**2;if(s<score){best=i;score=s}});samples.push(f.indices[best])}return{side:f.side,samples}});
 for(const r of routes)for(const reverse of [false,true]){const points=reverse?[...r.points].reverse():r.points,first=new T.Vector3(...points[0]),last=points.at(-1);w.setFocus(first);c.setFeetPosition(first);const initialDirection=new T.Vector3(...points[1]).sub(first);const yaw=Math.atan2(-initialDirection.x,-initialDirection.z);c.yaw=yaw;v.walk.presentation.reset(first,yaw);v.walk.keys.clear();a.resetFootIK?.();for(let j=0;j<30;j++)v.walk.update(1/60);let index=1,airborne=0,frames=0;const samples=[],states:any={},cpu:number[]=[];let beforeFoot:any={};
 for(;frames<7000&&index<points.length;frames++){const end=points[index],d=new T.Vector3(end[0]-c.position.x,0,end[2]-c.position.z),distance=d.length();if(distance<.045){index++;continue}c.yaw=Math.atan2(-d.x,-d.z);c.params.walkSpeed=Math.min(reverse?.4:.35,distance*60);v.walk.keys.add('KeyW');w.setFocus(c.position);const started=performance.now();v.walk.update(1/60);cpu.push(performance.now()-started);if(!c.onGround)airborne++;const state=v.walk.presentation.animation;states[state]=(states[state]||0)+1;if(frames%6===0){a.root.updateMatrixWorld(true);const action=a.actions.get(state),phase=action?action.time/action.getClip().duration:0;const feet=soleSets.map((f:any)=>{const legPhase=(phase+(f.side==='Left'?0:.5))%1,stance=/stairs/.test(state)&&legPhase>.08&&legPhase<(state==='stairsUp'?.49:.53);const bone=a.model.getObjectByName('mixamorig'+f.side+'Foot'),position=bone.getWorldPosition(new T.Vector3());const gaps=f.samples.map((s:any)=>{const mesh=a.model.getObjectByName(s.mesh),p=mesh.getVertexPosition(s.index,new T.Vector3()).applyMatrix4(mesh.matrixWorld),origin=p.clone().setY(c.position.y+.52),g=w.raycastBestGround(origin,1.2,c.params.maxSlope);return g?p.y-g.point.y:null}).filter((x:any)=>x!==null);const previous=beforeFoot[f.side],slip=stance&&previous?.stance&&legPhase>previous.phase?Math.hypot(position.x-previous.x,position.z-previous.z):null;beforeFoot[f.side]={x:position.x,z:position.z,stance,phase:legPhase};return{side:f.side,stance,phase:legPhase,minGap:gaps.length?Math.min(...gaps):null,maxGap:gaps.length?Math.max(...gaps):null,slip,position:position.toArray()}});samples.push({frame:frames,state,phase,controller:c.position.toArray(),feet,ik:a.footIK?.diagnostics?.()})}}
 v.walk.keys.clear();for(let j=0;j<90;j++)v.walk.update(1/60);results.push({name:r.name,reverse,frames,index,total:points.length,airborne,states,final:c.position.toArray(),distance:Math.hypot(last[0]-c.position.x,last[2]-c.position.z),afterStop:v.walk.presentation.animation,cpu:{mean:cpu.reduce((a,b)=>a+b,0)/cpu.length,p95:[...cpu].sort((a,b)=>a-b)[Math.floor(cpu.length*.95)],samples:cpu.length},samples});}
 v.walk.deactivate();c.params.walkSpeed=.35;return{enabled,results};
}
