import * as T from 'three'
export async function exercise(v:any){
 await v.character.load('/models/review-v4/Xbot-stairs-v4.glb');const a=v.character;a.setFootIKEnabled(true);const calibration=a.footIK.legs.map((l:any)=>l.sole.clone());let preserved=true;let lastPose:any[]=[];let lastModel=new T.Vector3();const apply=a.footIK.apply.bind(a.footIK);a.footIK.apply=(...args:any[])=>{const pose:any[]=[];a.model.traverse((b:any)=>{if(b.isBone)pose.push([b,b.position.clone(),b.scale.clone(),b.quaternion.clone()])});lastModel.copy(a.model.position);apply(...args);preserved&&=pose.every(([b,p,s])=>b.position.equals(p)&&b.scale.equals(s));lastPose=pose};const results=[];
 for(const rise of [.12,.1825,.19])for(const fps of [30,60,120])for(const reverse of [false,true]){
  a.resetFootIK();preserved=true;let smoothed=reverse?rise*10:0;let maxError=0,finite=true,maxRootError=0;const positions:any[]=[];const lengths:any[]=[];a.model.traverse((b:any)=>{if(b.isBone){positions.push([b,b.position.clone(),b.scale.clone()]);if(/UpLeg$|Leg$/.test(b.name)&&b.children[0])lengths.push([b,b.children[0],b.position.length()])}});
  for(let f=0;f<fps*8;f++){const z=reverse?-2.79+f/fps*.35:-.01-f/fps*.35,level=Math.max(0,Math.min(10,Math.floor(-z/.28))),feet=new T.Vector3(0,level*rise,z);smoothed+=(feet.y-smoothed)*(1-Math.exp(-16/fps));const state=reverse?'stairsDown':'stairsUp';a.syncFromController(feet,reverse?Math.PI:0,state,false,reverse?.875:1);a.update(1/fps,{grounded:true,speed:.35,visualFeetY:smoothed,ground:(p:T.Vector3,d:number)=>{const y=Math.max(0,Math.min(10,Math.floor(-p.z/.28)))*rise;return y<=p.y&&p.y-y<=d?y:null}});maxRootError=Math.max(maxRootError,a.root.position.distanceTo(feet));a.root.updateMatrixWorld(true);a.model.traverse((b:any)=>{if(!b.matrixWorld.elements.every(Number.isFinite))finite=false});for(const l of a.footIK.diagnostics().legs)if(l.weight>.95)maxError=Math.max(maxError,l.targetError)}
  const unchanged=preserved;a.footIK.restore();const restored=lastPose.every(([b,p,s,q])=>b.quaternion.equals(q))&&a.model.position.equals(lastModel);results.push({rise,fps,reverse,finite,maxRootError,unchanged,restored,maxTargetError:maxError});
 }
 // Exit paths must restore the exact mixer pose, also after a translated/rotated reload.
 const transitions=[];for(const state of ['idle','walking','running','stairsUp','stairsDown','jumping','idle']){a.syncFromController(new T.Vector3(10,4,30),1.1,state,false,1);for(let i=0;i<30;i++)a.update(1/60,{grounded:state!=='jumping',speed:state==='running'?3.2:.35,visualFeetY:4,ground:(p:T.Vector3)=>4});a.root.updateMatrixWorld(true);const before:any[]=[];a.model.traverse((b:any)=>{if(b.isBone)before.push(b.matrixWorld.elements.every(Number.isFinite))});transitions.push({state,finite:before.every(Boolean),ik:a.footIK.diagnostics()})}
 const exits=[];for(const mode of ['missing-ground','airborne','first-person','turn']){a.resetFootIK();const feet=new T.Vector3(10,4,30);a.syncFromController(feet,0,'stairsUp',false,1);for(let i=0;i<30;i++)a.update(1/60,{grounded:true,speed:.35,visualFeetY:4,ground:()=>4});if(mode==='first-person')a.syncFromController(feet,0,'stairsUp',true,1);if(mode==='turn'){for(let i=0;i<90;i++){a.syncFromController(feet,i/90*Math.PI/2,'idle',false,1);a.update(1/60,{grounded:true,speed:0,visualFeetY:4,ground:()=>4})}}else a.update(1/60,{grounded:mode!=='airborne',speed:.35,visualFeetY:4,ground:()=>mode==='missing-ground'?null:4});a.root.updateMatrixWorld(true);let finite=true;a.root.traverse((o:any)=>{finite&&=o.matrixWorld.elements.every(Number.isFinite)});exits.push({mode,finite,rootError:a.root.position.distanceTo(feet),ik:a.footIK.diagnostics()})}a.syncFromController(new T.Vector3(10,4,30),1.1,'idle',false,1);a.setFootIKEnabled(false);const off=a.footIK.diagnostics();await a.load('/models/review-v4/Xbot-stairs-v4.glb');const reload=a.footIK.diagnostics();const reloadCalibrationError=Math.max(...a.footIK.legs.map((l:any,i:number)=>l.sole.distanceTo(calibration[i])));return{results,transitions,exits,off,reload,reloadCalibrationError};
}
