import fs from'node:fs';import assert from'node:assert/strict';import{chromium}from'playwright';
const fast=process.argv.includes('--fast');const dir='../../evidence/escalators-v11.2',selected=JSON.parse(fs.readFileSync('../../evidence/teleport-v11/selected-routes.json')).filter(r=>!fast||['foyer-east','tr-stufen-001-0','tr-stufen-001-1','upper-east','obj-1og-fluchtweg014-branch-1'].includes(r.id));const b=await chromium.launch({channel:'msedge',headless:true}),p=await b.newPage({viewport:{width:1440,height:940}}),errors=[];p.on('pageerror',e=>errors.push(String(e)));await p.addInitScript(()=>sessionStorage.setItem('building-viewer-demo-unlocked','1'));
try{await p.goto('http://127.0.0.1:5204/demos/icm-building/index.html');await p.waitForFunction(()=>document.querySelector('.bv-loading')?.classList.contains('hidden')&&!window.__iomBuildingViewer.orbit.isAnimating(),{},{timeout:180000});await p.evaluate(()=>{const v=window.__iomBuildingViewer;v.cancelThumbnailTask();v.modelAnim.stop();v.mode='orbit';v.orbit.setEnabled(false);v.collision.setPlacementMode(false)});const results=[];
for(const r of selected){const row=await p.evaluate(({r,fast})=>{const v=window.__iomBuildingViewer,c=v.controller,w=v.collision,t=v.stairTeleports,walk=v.walk;const down=code=>window.dispatchEvent(new KeyboardEvent('keydown',{code,bubbles:true})),up=code=>window.dispatchEvent(new KeyboardEvent('keyup',{code,bubbles:true}));const step=()=>{w.beginFrame();w.setFocus(c.position);walk.update(1/60);t.update(true,1/60)};const upPortal=t.portals.find(p=>p.route.id===r.id&&p.up);const rounds=[];
for(const reverse of [false,true]){const portal=reverse?t.portals.find(p=>p.route.id===r.id&&!p.up):upPortal,end=reverse?1:0;walk.deactivate();t.update(false);document.activeElement?.blur();w.setQueryLayer(r.ends[end].layerId);const start=c.position.clone().fromArray(r.ends[end].approach);w.setFocus(start);c.setFeetPosition(start);walk.activate(false);c.yaw=r.ends[end].yaw;walk.presentation.reset(c.position,c.yaw);c.params.walkSpeed=fast?6.5:1.6;walk.cameraMode=reverse?'firstPerson':'thirdPerson';step();down('KeyW');let frames=0,transitionFrames=0,commitAt=-1,maxSourceDrift=0,from=null;
for(;frames<200;frames++){step();if(t.effect.active){transitionFrames++;if(!from)from=c.position.clone();if(!t.effect.transferred)maxSourceDrift=Math.max(maxSourceDrift,from.distanceTo(c.position));if(t.effect.transferred&&commitAt<0)commitAt=transitionFrames;}if(commitAt>=0&&!t.effect.active)break;}const arrived=c.position.clone();for(let i=0;i<120;i++){if(i%15===0)down('KeyW');step()}const heldDrift=c.position.distanceTo(arrived);up('KeyW');
// Exit and re-enter the destination circle with its tested corridor; no reset of the gate.
down('KeyW');let exited=false;for(let i=0;i<100;i++){step();if(c.position.distanceTo(arrived)>portal.destinationRadius+.38){exited=true;break}}up('KeyW');down('KeyS');let returned=false;for(let i=0;i<190;i++){step();if(c.position.distanceTo(portal.point)<.015&&!t.effect.active){returned=true;break}}up('KeyS');
rounds.push({reverse,active:t.readyPortals.length,frames,transitionFrames,commitAt,maxSourceDrift,arrivalError:arrived.distanceTo(portal.destination),heldDrift,exited,returned,returnError:c.position.distanceTo(portal.point),grounded:c.onGround,opacityRestored:t.effect.saved.length===0,overlayHidden:t.effect.veil.style.display==='none'});}
t.update(false);walk.deactivate();return{id:r.id,rounds};},{r,fast});results.push(row);fs.writeFileSync(dir+(fast?'/teleport-fast.json':'/teleport-roundtrips.json'),JSON.stringify({results,errors},null,2));console.log(row.id,row.rounds.map(r=>({ok:r.arrivalError<.015&&r.returned&&r.heldDrift<.005,active:r.active,err:r.arrivalError,back:r.returnError})));}
assert.deepEqual(errors,[]);assert.ok(results.every(r=>r.rounds.every(x=>x.arrivalError<.015&&x.returned&&x.heldDrift<.005&&x.grounded&&x.opacityRestored&&x.overlayHidden&&x.maxSourceDrift<.001)));
}finally{await b.close()}
