import fs from 'node:fs';import {chromium} from 'playwright';
const dir='../../evidence/escalators-v11.2';
const b=await chromium.launch({channel:'msedge',headless:true}),p=await b.newPage({viewport:{width:1500,height:950}});await p.addInitScript(()=>sessionStorage.setItem('building-viewer-demo-unlocked','1'));
try{await p.goto('http://127.0.0.1:5204/demos/icm-building/index.html');await p.waitForFunction(()=>document.querySelector('.bv-loading')?.classList.contains('hidden')&&!window.__iomBuildingViewer.orbit.isAnimating(),{},{timeout:180000});
const data=await p.evaluate(async()=>{const v=window.__iomBuildingViewer,w=v.collision;v.cancelThumbnailTask();v.modelAnim.stop();v.mode='orbit';v.orbit.setEnabled(false);w.setPlacementMode(false);w.setQueryLayer('icm-anim-2025');const V=v.controller.position.constructor,{isValidSpawnPoint}=await import('/src/collision/CharacterController.ts');const rows=[];
for(const z of [-31.4,-26.7])for(const [x,y] of [[-78.4,0],[-60.9,6]]){const feet=new V(x,y,z);w.setFocus(feet);const points=[];for(const [dx,dz] of [[0,0],...Array.from({length:12},(_,i)=>[Math.cos(i*Math.PI/6)*.7,Math.sin(i*Math.PI/6)*.7])]){const pos=feet.clone().add(new V(dx,0,dz)),h=w.raycastBestGround(pos.clone().add(new V(0,.12,0)),.24,.95,'icm-anim-2025');v.pegman.raycaster.near=0;v.pegman.raycaster.far=.3;v.pegman.raycaster.set(pos.clone().add(new V(0,.15,0)),new V(0,-1,0));const a=v.pegman.raycastVisualSurface();points.push({offset:[dx,dz],support:h&&{point:h.point.toArray(),normal:h.normal.toArray(),name:h.sourceName},visual:a&&{point:a.point.toArray(),normal:a.normal.toArray(),name:a.objectName},spawn:h&&isValidSpawnPoint(w,h.point,h.normal,v.controller.params)})}rows.push({feet:feet.toArray(),points})}
v.camera.position.set(-83,3.3,-29.05);v.camera.lookAt(-72,2.8,-29.05);v.camera.updateMatrixWorld();return rows});fs.writeFileSync(dir+'/landing-survey.json',JSON.stringify(data,null,2));console.log(JSON.stringify(data));await p.waitForTimeout(500);await p.screenshot({path:dir+'/before-front.png'});
await p.evaluate(()=>{const v=window.__iomBuildingViewer;v.camera.position.set(-55,9.7,-29.05);v.camera.lookAt(-67,5.3,-29.05);v.camera.updateMatrixWorld()});await p.waitForTimeout(500);await p.screenshot({path:dir+'/before-top.png'});
}finally{await b.close()}
