export const WOOD_FINISHES = {
  natural: {
    id: 'natural',
    label: 'Natural',
    caption: 'Open grain',
    swatch: '#cbb08a',
    swatchInner: '#e2c9a2',
    tint: '#d4b48a',
    gain: 1.02,
    contrast: 1.08,
    hue: 0.004,
    sat: 0.92,
    roughness: 0.36,
    stain: 0.14,
    clearcoat: 0.14,
    metalPreserve: 1,
  },
  cherry: {
    id: 'cherry',
    label: 'Warm Cherry',
    caption: 'Amber stain',
    swatch: '#8b3d2a',
    swatchInner: '#b85c3c',
    tint: '#8a3a24',
    gain: 0.88,
    contrast: 1.18,
    hue: -0.03,
    sat: 1.14,
    roughness: 0.34,
    stain: 0.64,
    clearcoat: 0.16,
    metalPreserve: 1,
  },
  walnut: {
    id: 'walnut',
    label: 'Walnut',
    caption: 'Deep figure',
    swatch: '#4a3224',
    swatchInner: '#6d4a34',
    tint: '#4a3224',
    gain: 0.7,
    contrast: 1.22,
    hue: 0.004,
    sat: 0.98,
    roughness: 0.33,
    stain: 0.7,
    clearcoat: 0.2,
    metalPreserve: 1,
  },
  dark: {
    id: 'dark',
    label: 'Dark Finish',
    caption: 'Quiet lacquer',
    swatch: '#241c18',
    swatchInner: '#3a2e28',
    tint: '#2c221c',
    gain: 0.5,
    contrast: 1.26,
    hue: -0.008,
    sat: 0.86,
    roughness: 0.3,
    stain: 0.82,
    clearcoat: 0.28,
    metalPreserve: 1,
  },
}

export const HARDWARE_FINISHES = {
  bright: {
    id: 'bright',
    label: 'Bright',
    caption: 'Nickel',
    swatch: '#d8d4cc',
    color: '#cfcabe',
    roughness: 0.22,
    metalness: 0.96,
  },
  brass: {
    id: 'brass',
    label: 'Warm Brass',
    caption: 'Aged gold',
    swatch: '#b9894a',
    color: '#c49a52',
    roughness: 0.3,
    metalness: 0.92,
  },
  dark: {
    id: 'dark',
    label: 'Dark',
    caption: 'Gunmetal',
    swatch: '#3a3530',
    color: '#4a4540',
    roughness: 0.38,
    metalness: 0.88,
  },
}

export const LIGHTING_PRESETS = {
  studio: {
    id: 'studio',
    label: 'Studio',
    background: '#efe8dc',
    floor: '#e8dfd0',
    envIntensity: 0.55,
    key: { color: '#fff6ea', intensity: 1.35, position: [2.4, 3.1, 2.2] },
    fill: { color: '#d9e3ee', intensity: 0.38, position: [-2.6, 1.4, 0.6] },
    rim: { color: '#fff3d6', intensity: 0.55, position: [-0.4, 2.4, -2.6] },
    ambient: 0.12,
    shadowOpacity: 0.38,
  },
  warm: {
    id: 'warm',
    label: 'Warm',
    background: '#ead9c4',
    floor: '#e3d0b8',
    envIntensity: 0.42,
    key: { color: '#ffd7a8', intensity: 1.2, position: [1.8, 2.6, 2.4] },
    fill: { color: '#f0c9a0', intensity: 0.32, position: [-2.2, 1.2, 0.8] },
    rim: { color: '#ffb56a', intensity: 0.4, position: [0.2, 2.2, -2.4] },
    ambient: 0.16,
    shadowOpacity: 0.32,
  },
}
